/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janela.cplus;

import entidade.cplus.Movenda;
import entidade.cplus.Movendaprod;
import entidade.cplus.Moventrada;
import entidade.cplus.Moventradaprod;
import entidade.cplus.Produto;
import entidade.cplus.Produtoestoque;
import entidade.integrador.ProdFornecedor;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import jpa.cplus.ProdutoJpaController;
import jpa.cplus.ProdutoestoqueJpaController;
import query.cplus.QueryCplus;
import query.integrador.QueryIntegrador;

/**
 *
 * @author leonardo
 */
public class RelatorioComprasJFrame extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioComprasJFrame
     *
     * @param managerIntegrador1
     * @param managerCplus1
     */
    public RelatorioComprasJFrame(EntityManagerFactory managerIntegrador1, EntityManagerFactory managerCplus1) {
        initComponents();

        formataCampos = new FormatacaoDeCampos();
        managerCplus = managerCplus1;
        managerIntegrador = managerIntegrador1;
        queryCplus = new QueryCplus(managerCplus);
        queryIntegrador = new QueryIntegrador(managerIntegrador);
        jDateChooserDataFinal.setDate(formataCampos.alteraDiaData(formataCampos.dataAtual(), 0));
        jDateChooserDataInicial.setDate(formataCampos.alteraDiaData(formataCampos.dataAtual(), -90));
        jTextFieldNumeroDiasCompra.setText("30");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icones/logo.png")));
        colunaCodprod = jTableRelatorio.getColumnModel().getColumnIndex("ID C-Plus");
        formataCampo = new FormatacaoDeCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        integradorPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("integradorPU").createEntityManager();
        jComboBox1 = new javax.swing.JComboBox();
        produtosAllnationsQuery = java.beans.Beans.isDesignTime() ? null : integradorPUEntityManager.createQuery("SELECT p FROM ProdFornecedor p WHERE p.ean = '88888888'");
        produtosAllnationsList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(new java.util.LinkedList(produtosAllnationsQuery.getResultList()));
        produtosAllnationsListProdutos = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(new java.util.LinkedList(produtosAllnationsQuery.getResultList()));
        jPanel1 = new javax.swing.JPanel();
        jPanelFiltros = new javax.swing.JPanel();
        jPanelPesquisa = new javax.swing.JPanel();
        jLabelEstadoFornecedor = new javax.swing.JLabel();
        jLabelFornecedor = new javax.swing.JLabel();
        jLabelDataInicial = new javax.swing.JLabel();
        jDateChooserDataInicial = new com.toedter.calendar.JDateChooser();
        jComboBoxFornecedor = new javax.swing.JComboBox();
        jComboBoxEstadoFornecedor = new javax.swing.JComboBox();
        jLabelDataFinal = new javax.swing.JLabel();
        jLabelComprasPara = new javax.swing.JLabel();
        jDateChooserDataFinal = new com.toedter.calendar.JDateChooser();
        jTextFieldNumeroDiasCompra = new javax.swing.JTextField();
        jLabelDias = new javax.swing.JLabel();
        jCheckBoxDisponivelFornecedor = new javax.swing.JCheckBox();
        jCheckBoxSomenteProdutosCompra = new javax.swing.JCheckBox();
        jButtonPesqiosar = new javax.swing.JButton();
        jCheckBoxCalculaSujestao = new javax.swing.JCheckBox();
        jPanelInformacoes = new javax.swing.JPanel();
        jLabelDataultimaCompra = new javax.swing.JLabel();
        jTextFieldDataUltimaCompra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUltimaQuantidadeComprada = new javax.swing.JTextField();
        jLabelDataUltimaVenda = new javax.swing.JLabel();
        jTextFieldDataUltimaVenda = new javax.swing.JTextField();
        jLabelPrecoCusto = new javax.swing.JLabel();
        jTextFieldPrecoCusto = new javax.swing.JTextField();
        jLabelValorSt = new javax.swing.JLabel();
        jTextFieldValorSubstituicaoTributaria = new javax.swing.JTextField();
        jLabelCustoReal = new javax.swing.JLabel();
        jTextFieldCustoReal = new javax.swing.JTextField();
        jLabelPrecoPutrosCustos = new javax.swing.JLabel();
        jTextFieldPercOutrosCustos = new javax.swing.JTextField();
        jTextFieldFornecedor = new javax.swing.JTextField();
        jLabelEstoqueDisponivel = new javax.swing.JLabel();
        jTextFieldEstoqueDisponivel = new javax.swing.JTextField();
        jTabbedPaneGuias = new javax.swing.JTabbedPane();
        jPanelRelatorio = new javax.swing.JPanel();
        jScrollPaneRelatorio = new javax.swing.JScrollPane();
        jTableRelatorio = new javax.swing.JTable();
        jPanelFornecedor = new javax.swing.JPanel();
        jScrollPaneFornecedores = new javax.swing.JScrollPane();
        jTableFornecedores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonCalculaSujestao = new javax.swing.JButton();
        jLabelSugestao = new javax.swing.JLabel();
        jTextFieldSujestao = new javax.swing.JTextField();
        jLabelMediaDiaria = new javax.swing.JLabel();
        jTextFieldMediaDiaria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooserInicioAvaliacao = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserFimAvaliacao = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNumeroDiasCalculo = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Compras");

        jPanelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Flitros"));

        jPanelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jLabelEstadoFornecedor.setText("Estado Forne:");

        jLabelFornecedor.setText("Fornecedor:");

        jLabelDataInicial.setText("Data Inicial:");

        jComboBoxFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aldo", "All Nations", "Alcatéia", "Agis", "Colecao", "Oderço" }));
        jComboBoxFornecedor.setToolTipText("");

        jComboBoxEstadoFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "ES", "PR", "SP", "RJ", "SC", "MG" }));

        jLabelDataFinal.setText("Data Final:");

        jLabelComprasPara.setText("Compras para:");

        jLabelDias.setText("dias.");

        jCheckBoxDisponivelFornecedor.setSelected(true);
        jCheckBoxDisponivelFornecedor.setText("Disponivel Fornecedor:");

        jCheckBoxSomenteProdutosCompra.setText("Somente Produtos para Compra:");

        jButtonPesqiosar.setText("Pesquisar");
        jButtonPesqiosar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesqiosarActionPerformed(evt);
            }
        });

        jCheckBoxCalculaSujestao.setText("Calcular Sujestão de Compra");

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEstadoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxEstadoFornecedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                    .addComponent(jButtonPesqiosar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabelDataFinal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                            .addComponent(jLabelComprasPara)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNumeroDiasCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelDias))
                        .addComponent(jCheckBoxDisponivelFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jCheckBoxSomenteProdutosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxCalculaSujestao, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataInicial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFornecedor)
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstadoFornecedor))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPesqiosar))
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataFinal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComprasPara, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumeroDiasCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxDisponivelFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxSomenteProdutosCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCalculaSujestao))
        );

        jPanelInformacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jLabelDataultimaCompra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDataultimaCompra.setText("Data Ultima Compra:");
        jLabelDataultimaCompra.setFocusable(false);
        jLabelDataultimaCompra.setRequestFocusEnabled(false);

        jTextFieldDataUltimaCompra.setEnabled(false);
        jTextFieldDataUltimaCompra.setFocusable(false);
        jTextFieldDataUltimaCompra.setRequestFocusEnabled(false);

        jLabel2.setText("Ultima Qtd. Com.:");

        jTextFieldUltimaQuantidadeComprada.setEnabled(false);

        jLabelDataUltimaVenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDataUltimaVenda.setText("Data Ultima Venda:");
        jLabelDataUltimaVenda.setFocusable(false);
        jLabelDataUltimaVenda.setRequestFocusEnabled(false);

        jTextFieldDataUltimaVenda.setEnabled(false);
        jTextFieldDataUltimaVenda.setFocusable(false);
        jTextFieldDataUltimaVenda.setRequestFocusEnabled(false);

        jLabelPrecoCusto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrecoCusto.setText("Preço Custo: R$");
        jLabelPrecoCusto.setFocusable(false);
        jLabelPrecoCusto.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabelPrecoCusto.setMinimumSize(new java.awt.Dimension(100, 14));

        jTextFieldPrecoCusto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPrecoCusto.setEnabled(false);
        jTextFieldPrecoCusto.setFocusable(false);
        jTextFieldPrecoCusto.setRequestFocusEnabled(false);

        jLabelValorSt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelValorSt.setText("Valor S.T.: R$");
        jLabelValorSt.setFocusable(false);
        jLabelValorSt.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabelValorSt.setMinimumSize(new java.awt.Dimension(100, 14));

        jTextFieldValorSubstituicaoTributaria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldValorSubstituicaoTributaria.setEnabled(false);
        jTextFieldValorSubstituicaoTributaria.setFocusable(false);
        jTextFieldValorSubstituicaoTributaria.setRequestFocusEnabled(false);

        jLabelCustoReal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCustoReal.setText("Custo Real: R$");
        jLabelCustoReal.setFocusable(false);
        jLabelCustoReal.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabelCustoReal.setMinimumSize(new java.awt.Dimension(100, 14));

        jTextFieldCustoReal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCustoReal.setEnabled(false);
        jTextFieldCustoReal.setFocusable(false);
        jTextFieldCustoReal.setRequestFocusEnabled(false);

        jLabelPrecoPutrosCustos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPrecoPutrosCustos.setText("Custo Opera. : %");
        jLabelPrecoPutrosCustos.setFocusable(false);
        jLabelPrecoPutrosCustos.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabelPrecoPutrosCustos.setMinimumSize(new java.awt.Dimension(100, 14));

        jTextFieldPercOutrosCustos.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldPercOutrosCustos.setFocusable(false);
        jTextFieldPercOutrosCustos.setRequestFocusEnabled(false);

        jLabelEstoqueDisponivel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelEstoqueDisponivel.setText("Estoque Disponível:");
        jLabelEstoqueDisponivel.setFocusable(false);
        jLabelEstoqueDisponivel.setRequestFocusEnabled(false);

        jTextFieldEstoqueDisponivel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldEstoqueDisponivel.setToolTipText("");
        jTextFieldEstoqueDisponivel.setEnabled(false);
        jTextFieldEstoqueDisponivel.setFocusable(false);
        jTextFieldEstoqueDisponivel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelInformacoesLayout = new javax.swing.GroupLayout(jPanelInformacoes);
        jPanelInformacoes.setLayout(jPanelInformacoesLayout);
        jPanelInformacoesLayout.setHorizontalGroup(
            jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelDataUltimaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDataultimaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelEstoqueDisponivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldUltimaQuantidadeComprada, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextFieldDataUltimaCompra)
                            .addComponent(jTextFieldDataUltimaVenda))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldEstoqueDisponivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPrecoCusto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCustoReal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPrecoPutrosCustos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelValorSt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPrecoCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jTextFieldCustoReal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldValorSubstituicaoTributaria, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPercOutrosCustos)))
            .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelInformacoesLayout.setVerticalGroup(
            jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataUltimaVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDataUltimaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDataultimaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDataUltimaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(37, 37, 37))
                    .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCustoReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCustoReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelValorSt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldValorSubstituicaoTributaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldUltimaQuantidadeComprada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecoPutrosCustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPercOutrosCustos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstoqueDisponivel)
                            .addComponent(jTextFieldEstoqueDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelFiltrosLayout = new javax.swing.GroupLayout(jPanelFiltros);
        jPanelFiltros.setLayout(jPanelFiltrosLayout);
        jPanelFiltrosLayout.setHorizontalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFiltrosLayout.setVerticalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTableRelatorio.setAutoCreateRowSorter(true);
        jTableRelatorio.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, produtosAllnationsList, jTableRelatorio);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ean}"));
        columnBinding.setColumnName("Ean");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Descricao Fornecedor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${garantia}"));
        columnBinding.setColumnName("Estoq Atual");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoFornecedor}"));
        columnBinding.setColumnName("Cod Fornecedor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoCusto}"));
        columnBinding.setColumnName("Preco Custo");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoCustoComSt}"));
        columnBinding.setColumnName("Preco Cus St");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${estoque}"));
        columnBinding.setColumnName("Estado");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${disponivel}"));
        columnBinding.setColumnName("Disponivel");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ultimaImportacao}"));
        columnBinding.setColumnName("Ultima Importacao");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${substTributaria}"));
        columnBinding.setColumnName("Subst Tributaria");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${partNumber}"));
        columnBinding.setColumnName("Part Number");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${origemProduto}"));
        columnBinding.setColumnName("Origem Produto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ncm}"));
        columnBinding.setColumnName("Ncm");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fabricante}"));
        columnBinding.setColumnName("Fabricante");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departamento}"));
        columnBinding.setColumnName("Departamento");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ativo}"));
        columnBinding.setColumnName("Ativo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${referenceCplus}"));
        columnBinding.setColumnName("ID C-Plus");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jTableRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRelatorioMouseClicked(evt);
            }
        });
        jScrollPaneRelatorio.setViewportView(jTableRelatorio);
        if (jTableRelatorio.getColumnModel().getColumnCount() > 0) {
            jTableRelatorio.getColumnModel().getColumn(0).setMinWidth(120);
            jTableRelatorio.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableRelatorio.getColumnModel().getColumn(0).setMaxWidth(300);
            jTableRelatorio.getColumnModel().getColumn(1).setPreferredWidth(350);
            jTableRelatorio.getColumnModel().getColumn(3).setMinWidth(80);
            jTableRelatorio.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTableRelatorio.getColumnModel().getColumn(3).setMaxWidth(300);
            jTableRelatorio.getColumnModel().getColumn(4).setCellRenderer(new integrador.render.RenderPreco());
            jTableRelatorio.getColumnModel().getColumn(5).setCellRenderer(new integrador.render.RenderPreco());
            jTableRelatorio.getColumnModel().getColumn(9).setCellRenderer(new integrador.render.RenderPreco());
            jTableRelatorio.getColumnModel().getColumn(16).setResizable(false);
        }

        javax.swing.GroupLayout jPanelRelatorioLayout = new javax.swing.GroupLayout(jPanelRelatorio);
        jPanelRelatorio.setLayout(jPanelRelatorioLayout);
        jPanelRelatorioLayout.setHorizontalGroup(
            jPanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
        );
        jPanelRelatorioLayout.setVerticalGroup(
            jPanelRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        jTabbedPaneGuias.addTab("Relatório", jPanelRelatorio);

        jTableFornecedores.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, produtosAllnationsListProdutos, jTableFornecedores);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${departamento}"));
        columnBinding.setColumnName("Fornecedor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${estoque}"));
        columnBinding.setColumnName("Estoque");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoCusto}"));
        columnBinding.setColumnName("Preco Custo");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoCustoComSt}"));
        columnBinding.setColumnName("Preco Custo Com St");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${porcentagemOutrosCustos}"));
        columnBinding.setColumnName("Porcentagem Outros Custos");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valorStRs}"));
        columnBinding.setColumnName("Valor St Rs");
        columnBinding.setColumnClass(java.math.BigDecimal.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${origemProduto}"));
        columnBinding.setColumnName("Origem Produto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ultimaImportacao}"));
        columnBinding.setColumnName("Ultima Importacao");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fabricante}"));
        columnBinding.setColumnName("Fabricante");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ean}"));
        columnBinding.setColumnName("Ean");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${disponivel}"));
        columnBinding.setColumnName("Disponivel");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigo}"));
        columnBinding.setColumnName("Codigo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ativo}"));
        columnBinding.setColumnName("Ativo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${partNumber}"));
        columnBinding.setColumnName("Part Number");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPaneFornecedores.setViewportView(jTableFornecedores);
        if (jTableFornecedores.getColumnModel().getColumnCount() > 0) {
            jTableFornecedores.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTableFornecedores.getColumnModel().getColumn(2).setCellRenderer(new integrador.render.RenderPreco());
            jTableFornecedores.getColumnModel().getColumn(3).setCellRenderer(new integrador.render.RenderPreco());
            jTableFornecedores.getColumnModel().getColumn(5).setCellRenderer(new integrador.render.RenderPreco());
            jTableFornecedores.getColumnModel().getColumn(14).setPreferredWidth(250);
        }

        jButtonCalculaSujestao.setText("Calcular Sugestão");
        jButtonCalculaSujestao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculaSujestaoActionPerformed(evt);
            }
        });

        jLabelSugestao.setText("Sugestão:");

        jLabelMediaDiaria.setText("Média Diária:");

        jLabel1.setText("Príodo de Avaliação:");

        jLabel3.setText("À:");

        jLabel4.setText("Número de Dias do Cálculo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCalculaSujestao)
                .addGap(59, 59, 59)
                .addComponent(jLabelSugestao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSujestao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMediaDiaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldMediaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserInicioAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserFimAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNumeroDiasCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonCalculaSujestao)
                .addComponent(jLabelSugestao)
                .addComponent(jTextFieldSujestao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelMediaDiaria)
                .addComponent(jTextFieldMediaDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel3)
                .addComponent(jDateChooserInicioAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jDateChooserFimAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jTextFieldNumeroDiasCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelFornecedorLayout = new javax.swing.GroupLayout(jPanelFornecedor);
        jPanelFornecedor.setLayout(jPanelFornecedorLayout);
        jPanelFornecedorLayout.setHorizontalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 1057, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFornecedorLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFornecedorLayout.setVerticalGroup(
            jPanelFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFornecedorLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneGuias.addTab("Fornecedores", jPanelFornecedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFiltros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106))
            .addComponent(jTabbedPaneGuias, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneGuias, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesqiosarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesqiosarActionPerformed
        listagemPorFornecedor();
    }//GEN-LAST:event_jButtonPesqiosarActionPerformed

    private void jTableRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRelatorioMouseClicked
        idProdCplus = jTableRelatorio.getValueAt(jTableRelatorio.getSelectedRow(), colunaCodprod).toString();
        produtoCplus = new ProdutoJpaController(managerCplus).findProduto(idProdCplus);
        if (produtoCplus.getDatreaj() != null) {
            // jTextFieldDataUltimoReajuste.setText(formataCampo.dataStringSoData(produtoCplus.getDatreaj(), 0));
        }
        if(produtoCplus.getValoripi() != null){
        jTextFieldPrecoCusto.setText(formataCampo.bigDecimalParaString(produtoCplus.getPrecusto().add(produtoCplus.getValoripi()), 2));
        }
        jTextFieldCustoReal.setText(formataCampo.bigDecimalParaString(produtoCplus.getCustoreal(), 2));
        //jTextFieldValorIpi.setText(formataCampo.bigDecimalParaString(produtoCplus.getValoripi(), 2));
        jTextFieldValorSubstituicaoTributaria.setText(formataCampo.bigDecimalParaString(produtoCplus.getValorsubsttributaria(), 2));
        jTextFieldPercOutrosCustos.setText(formataCampo.bigDecimalParaString(produtoCplus.getPercoutroscustos(), 2));
        char compra = 'C';
        List<Moventrada> listMovEntrada = queryCplus.resultUltimaCompra(idProdCplus, compra, 1);
        for (Moventrada movEnt : listMovEntrada) {
            jTextFieldDataUltimaCompra.setText(formataCampo.dataStringSoData(movEnt.getData(), 0));
            if (movEnt.getCodForn() != null) {
                jTextFieldFornecedor.setText(movEnt.getCodForn().getNomeforn());
            }
            for (Moventradaprod movPro : queryCplus.resultProdutoEntrada(idProdCplus, movEnt.getCodmoventr())) {

                jTextFieldUltimaQuantidadeComprada.setText(formataCampo.bigDecimalParaString(movPro.getQuantidade(), 0));

            }
        }
        char venda = 'V';
        List<Movenda> listMovVenda = queryCplus.resultUltimaVenda(idProdCplus, venda, 1);
        for (Movenda movVen : listMovVenda) {
            jTextFieldDataUltimaVenda.setText(formataCampo.dataStringSoData(movVen.getData(), 0));
        }
        for (Produtoestoque estoque : queryCplus.resultTodosEstoques(idProdCplus)) {
            if ("000000001".equals(estoque.getSetorestoque().getCodsetorestoque())) {
                BigDecimal estoqueDisponivel = estoque.getEstatu().subtract(estoque.getReservadoorcamento()).subtract(estoque.getReservadoos());
                jTextFieldEstoqueDisponivel.setText(formataCampo.bigDecimalParaString(estoqueDisponivel, 0));
            }
        }
        produtosAllnationsListProdutos.clear();
        for (ProdFornecedor proAll : queryIntegrador.listProdFornecedor(idProdCplus, 1)) {
            produtosAllnationsListProdutos.add(proAll);
        }
        limpaCampos();
    }//GEN-LAST:event_jTableRelatorioMouseClicked

    private void jButtonCalculaSujestaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculaSujestaoActionPerformed
        if (idProdCplus != null) {
            for (Produto prodInt : queryCplus.listProduto(idProdCplus)) {
                double sugestao = 0.00;
                double mediaDiaria;
                mediaDiaria = mediaVendaProduto(prodInt.getCodprod());
                sugestao = mediaDiaria * Double.valueOf(jTextFieldNumeroDiasCompra.getText());
                sugestao = sugestao;
                if (sugestao < 1.00) {
                    sugestao = 0.00;
                }
                jTextFieldSujestao.setText(String.valueOf((int) sugestao));
                jDateChooserInicioAvaliacao.setDate(inicioAvaliacao);
                jDateChooserFimAvaliacao.setDate(fimAvaliacao);
                jTextFieldMediaDiaria.setText(formataCampo.bigDecimalParaString(new BigDecimal(mediaDiaria).setScale(3, BigDecimal.ROUND_HALF_UP), 3));
                jTextFieldNumeroDiasCalculo.setText(formataCampo.bigDecimalParaString(numerodeDiasCalculo, 0));
            }
        }
    }//GEN-LAST:event_jButtonCalculaSujestaoActionPerformed

    private void limpaCampos() {
        jTextFieldSujestao.setText("");
        jDateChooserInicioAvaliacao.setDate(null);
        jDateChooserFimAvaliacao.setDate(null);
        jTextFieldMediaDiaria.setText("");
        jTextFieldNumeroDiasCalculo.setText("");
    }

    private void listagemPorFornecedor() {
        String forn = "";
        List<ProdFornecedor> listProdFor;
        switch (jComboBoxFornecedor.getSelectedIndex()) {
            case 0:
                forn = "ALDO";
                break;
            case 1:
                forn = "ALL NATIONS";
                break;
            case 2:
                forn = "ALCATEIA";
                break;
            case 3:
                forn = "AGIS";
                break;
            case 4:
                forn = "COLECAO";
                break;
            case 5:
                forn = "ODERCO";
                break;
        }
        int disp = 0;
        if (jCheckBoxDisponivelFornecedor.isSelected()) {
            disp = 1;
        }
        switch (jComboBoxEstadoFornecedor.getSelectedIndex()) {
            case 0:
                listProdFor = queryIntegrador.listaProdFornecedor(forn, disp);
                break;
            case 1:
                listProdFor = queryIntegrador.resultFornecedor(forn, "ES", disp);
                break;
            case 2:
                listProdFor = queryIntegrador.resultFornecedor(forn, "PR", disp);
                break;
            case 3:
                listProdFor = queryIntegrador.resultFornecedor(forn, "SP", disp);
                break;
            case 4:
                listProdFor = queryIntegrador.resultFornecedor(forn, "RJ", disp);
                break;
            case 5:
                listProdFor = queryIntegrador.resultFornecedor(forn, "SC", disp);
                break;
            case 6:
                listProdFor = queryIntegrador.resultFornecedor(forn, "MG", disp);
                break;
            default:
                listProdFor = queryIntegrador.listaProdFornecedorDisponivel(forn, disp);
        }

        produtosAllnationsList.clear();
        for (ProdFornecedor prodFor : listProdFor) {
            boolean condicao = true;
            double sugestao = 0.00;
            double mediaDiaria;
            if (jCheckBoxCalculaSujestao.isSelected()) {
                mediaDiaria = mediaVendaProduto(prodFor.getReferenceCplus());
            } else {
                mediaDiaria = 1.00;
            }

            if (jCheckBoxSomenteProdutosCompra.isSelected()) {
                sugestao = mediaDiaria * Double.valueOf(jTextFieldNumeroDiasCompra.getText());
                // sugestao = sugestao - prodFor.getIdProduto().getEstoque().doubleValue();
                sugestao = sugestao;
                if (sugestao < 1.00) {
                    condicao = false;
                }
            }

            prodFor.setGarantia(estoqueCplus(prodFor.getReferenceCplus()));

            if (condicao) {
                //   prodFor.getIdProduto.setSugestaoCompra((int) sugestao);
                //  prodFor.getIdProduto().setPeriodoAvaliacaoInicio(inicioAvaliacao);
                //   prodFor.getIdProduto().setPeriodoAvalicaoFim(fimAvaliacao);
                //   prodFor.getIdProduto().setMediaDiariaVenda(new BigDecimal(mediaDiaria).setScale(3, BigDecimal.ROUND_HALF_UP));
                produtosAllnationsList.add(prodFor);
            }
        }
    }

    private int estoqueCplus(String codProduto) {
        int estoqueDisponivel = 0;
        List<Produtoestoque> listEsroque = queryCplus.listProdutoEstoque(codProduto);
        for (Produtoestoque est : listEsroque) {
             estoqueDisponivel = est.getEstatu().intValue() - est.getReservadoorcamento().intValue() - est.getReservadoos().intValue();
        }
        return estoqueDisponivel;
    }

    private double mediaVendaProduto(String codProdCplus) {
        BigDecimal totalVendas = BigDecimal.ZERO;
        numerodeDiasCalculo = BigDecimal.ZERO;
        boolean comEstoque = false;
        List<Movendaprod> listaVendaProdData;
        List<Moventradaprod> listEntradaProdData = queryCplus.resultProdutoEntrada(codProdCplus, 'C', jDateChooserDataInicial.getDate(), jDateChooserDataFinal.getDate());
        List<Produtoestoque> listEsroque = queryCplus.listProdutoEstoque(codProdCplus);
        for (Produtoestoque est : listEsroque) {
            int estoqueDisponivel = est.getEstatu().intValue() - est.getReservadoorcamento().intValue() - est.getReservadoos().intValue();
            if (estoqueDisponivel > 0) {
                comEstoque = true;
            }
        }
        if (listEntradaProdData.isEmpty()) {
            List<Moventradaprod> listEntradaProd = queryCplus.resultProdutoEntrada(codProdCplus, true, 1);
            Date primeiraDataCompra = jDateChooserDataFinal.getDate();
            for (Moventradaprod entradaProd : listEntradaProd) {
                if (comparaDatas(entradaProd.getCodmoventr().getData(), primeiraDataCompra)) {
                    primeiraDataCompra = entradaProd.getCodmoventr().getData();
                }
            }
            if (comEstoque) {
                listaVendaProdData = queryCplus.resultProdutoVenda(codProdCplus, 'V', primeiraDataCompra, jDateChooserDataFinal.getDate());
                numerodeDiasCalculo = diferencaDeDias(primeiraDataCompra, jDateChooserDataFinal.getDate());
                inicioAvaliacao = primeiraDataCompra;
                fimAvaliacao = jDateChooserDataFinal.getDate();
                for (Movendaprod vendaProd : listaVendaProdData) {
                    totalVendas = totalVendas.add(vendaProd.getQuantidade());
                }
            } else {
                List<Movendaprod> listaVendaProd = queryCplus.resultProdutoVenda(codProdCplus, true, 1);
                for (Movendaprod prodUltimo : listaVendaProd) {
                    listaVendaProdData = queryCplus.resultProdutoVenda(codProdCplus, 'V', primeiraDataCompra, prodUltimo.getCodmovenda().getData());
                    numerodeDiasCalculo = diferencaDeDias(primeiraDataCompra, prodUltimo.getCodmovenda().getData());
                    inicioAvaliacao = primeiraDataCompra;
                    fimAvaliacao = prodUltimo.getCodmovenda().getData();
                    for (Movendaprod vendaProd : listaVendaProdData) {
                        totalVendas = totalVendas.add(vendaProd.getQuantidade());
                    }
                }
            }
        } else {
            if (comEstoque) {
                listaVendaProdData = queryCplus.resultProdutoVenda(codProdCplus, 'V', jDateChooserDataInicial.getDate(), jDateChooserDataFinal.getDate());
                numerodeDiasCalculo = diferencaDeDias(jDateChooserDataInicial.getDate(), jDateChooserDataFinal.getDate());
                inicioAvaliacao = jDateChooserDataInicial.getDate();
                fimAvaliacao = jDateChooserDataFinal.getDate();
                for (Movendaprod vendaProd : listaVendaProdData) {
                    totalVendas = totalVendas.add(vendaProd.getQuantidade());
                }
            } else {
                List<Movendaprod> listaVendaProd = queryCplus.resultProdutoVenda(codProdCplus, true, 1);
                for (Movendaprod prodUltimo : listaVendaProd) {
                    listaVendaProdData = queryCplus.resultProdutoVenda(codProdCplus, 'V', jDateChooserDataInicial.getDate(), prodUltimo.getCodmovenda().getData());
                    numerodeDiasCalculo = diferencaDeDias(jDateChooserDataInicial.getDate(), prodUltimo.getCodmovenda().getData());
                    inicioAvaliacao = jDateChooserDataInicial.getDate();
                    fimAvaliacao = prodUltimo.getCodmovenda().getData();
                    for (Movendaprod vendaProd : listaVendaProdData) {
                        totalVendas = totalVendas.add(vendaProd.getQuantidade());
                    }
                }
            }
        }
        BigDecimal totBig;
        if (numerodeDiasCalculo.doubleValue() == 0.00) {
            totBig = totalVendas;
        } else {
            totBig = totalVendas.divide(numerodeDiasCalculo, 3, RoundingMode.UP);
        }
        //BigDecimal totBig = new BigDecimal(tot).setScale(3, BigDecimal.ROUND_HALF_UP);
        return totBig.doubleValue();
    }

    private BigDecimal diferencaDeDias(Date primeiraData, Date segundaData) {
        int nDias = 0;
        Calendar segundaDataCalendar = Calendar.getInstance();
        Calendar primeiraDataCalendar = Calendar.getInstance();
        segundaDataCalendar.setTime(segundaData);
        primeiraDataCalendar.setTime(primeiraData);
        nDias = (segundaDataCalendar.get(Calendar.YEAR) * 365 + segundaDataCalendar.get(Calendar.DAY_OF_YEAR)) - (primeiraDataCalendar.get(Calendar.YEAR) * 365 + primeiraDataCalendar.get(Calendar.DAY_OF_YEAR));
        return new BigDecimal(nDias);
    }

    private boolean comparaDatas(Date primeiraData, Date segundaData) {
        boolean condicao = false;
        Calendar segundaDataCalendar = Calendar.getInstance();
        Calendar primeiraDataCalendar = Calendar.getInstance();
        segundaDataCalendar.setTime(segundaData);
        primeiraDataCalendar.setTime(primeiraData);
        String diaAtualStr = String.format("%02d", segundaDataCalendar.get(Calendar.DAY_OF_MONTH));
        String mesAtualStr = String.format("%02d", segundaDataCalendar.get(Calendar.MONTH));
        String anoAtualStr = String.format("%04d", segundaDataCalendar.get(Calendar.YEAR));
        int totalSegundaData = Integer.valueOf(anoAtualStr + mesAtualStr + diaAtualStr);

        String diaBancoStr = String.format("%02d", primeiraDataCalendar.get(Calendar.DAY_OF_MONTH));
        String mesBancoStr = String.format("%02d", primeiraDataCalendar.get(Calendar.MONTH));
        String anoBancoStr = String.format("%04d", primeiraDataCalendar.get(Calendar.YEAR));
        int totalPrimeiraData = Integer.valueOf(anoBancoStr + mesBancoStr + diaBancoStr);
        if (totalSegundaData <= totalPrimeiraData) {
            condicao = false;
        } else {
            condicao = true;
        }
        return condicao;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioComprasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioComprasJFrame(managerIntegrador, managerCplus).setVisible(true);
            }
        });
    }

    static EntityManagerFactory managerCplus;
    private static EntityManagerFactory managerIntegrador;
    private final FormatacaoDeCampos formataCampos;
    private final QueryCplus queryCplus;
    private BigDecimal numerodeDiasCalculo;
    private final QueryIntegrador queryIntegrador;
    private Date inicioAvaliacao;
    private Date fimAvaliacao;
    int colunaCodprod;
    Produto produtoCplus;
    FormatacaoDeCampos formataCampo;
    private String idProdCplus;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager integradorPUEntityManager;
    private javax.swing.JButton jButtonCalculaSujestao;
    private javax.swing.JButton jButtonPesqiosar;
    private javax.swing.JCheckBox jCheckBoxCalculaSujestao;
    private javax.swing.JCheckBox jCheckBoxDisponivelFornecedor;
    private javax.swing.JCheckBox jCheckBoxSomenteProdutosCompra;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxEstadoFornecedor;
    private javax.swing.JComboBox jComboBoxFornecedor;
    private com.toedter.calendar.JDateChooser jDateChooserDataFinal;
    private com.toedter.calendar.JDateChooser jDateChooserDataInicial;
    private com.toedter.calendar.JDateChooser jDateChooserFimAvaliacao;
    private com.toedter.calendar.JDateChooser jDateChooserInicioAvaliacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelComprasPara;
    private javax.swing.JLabel jLabelCustoReal;
    private javax.swing.JLabel jLabelDataFinal;
    private javax.swing.JLabel jLabelDataInicial;
    private javax.swing.JLabel jLabelDataUltimaVenda;
    private javax.swing.JLabel jLabelDataultimaCompra;
    private javax.swing.JLabel jLabelDias;
    private javax.swing.JLabel jLabelEstadoFornecedor;
    private javax.swing.JLabel jLabelEstoqueDisponivel;
    private javax.swing.JLabel jLabelFornecedor;
    private javax.swing.JLabel jLabelMediaDiaria;
    private javax.swing.JLabel jLabelPrecoCusto;
    private javax.swing.JLabel jLabelPrecoPutrosCustos;
    private javax.swing.JLabel jLabelSugestao;
    private javax.swing.JLabel jLabelValorSt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFiltros;
    private javax.swing.JPanel jPanelFornecedor;
    private javax.swing.JPanel jPanelInformacoes;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JPanel jPanelRelatorio;
    private javax.swing.JScrollPane jScrollPaneFornecedores;
    private javax.swing.JScrollPane jScrollPaneRelatorio;
    private javax.swing.JTabbedPane jTabbedPaneGuias;
    private javax.swing.JTable jTableFornecedores;
    private javax.swing.JTable jTableRelatorio;
    private javax.swing.JTextField jTextFieldCustoReal;
    private javax.swing.JTextField jTextFieldDataUltimaCompra;
    private javax.swing.JTextField jTextFieldDataUltimaVenda;
    private javax.swing.JTextField jTextFieldEstoqueDisponivel;
    private javax.swing.JTextField jTextFieldFornecedor;
    private javax.swing.JTextField jTextFieldMediaDiaria;
    private javax.swing.JTextField jTextFieldNumeroDiasCalculo;
    private javax.swing.JTextField jTextFieldNumeroDiasCompra;
    private javax.swing.JTextField jTextFieldPercOutrosCustos;
    private javax.swing.JTextField jTextFieldPrecoCusto;
    private javax.swing.JTextField jTextFieldSujestao;
    private javax.swing.JTextField jTextFieldUltimaQuantidadeComprada;
    private javax.swing.JTextField jTextFieldValorSubstituicaoTributaria;
    private java.util.List<entidade.integrador.ProdFornecedor> produtosAllnationsList;
    private java.util.List<entidade.integrador.ProdFornecedor> produtosAllnationsListProdutos;
    private javax.persistence.Query produtosAllnationsQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
