/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janela.prestaShop;

import entidade.prestaShop.PsCustomer;
import entidade.prestaShop.PsOrders;
import integrador.render.ConfTabelaSaidasPrestaShop;
import janela.cplus.FormataCampos;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jpa.prestaShop.PsOrdersJpaController;
import prestashop.Manager;
import query.prestaShop.QueryPrestaShop;

/**
 *
 * @author leonardo
 */
public class SaidasPrestaShopJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ListagemSaidasMagentoJDialog
     *
     * @param parent
     * @param modal
     */
    public SaidasPrestaShopJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);      
        //managerIntegrador = managerIntegrador1;
       // managerPrestaShop = managerPrestaShop1;
        queryPrestaShop = new QueryPrestaShop();
        initComponents();
        idOrder = jTableOrders.getColumnModel().getColumnIndex("Id Order");
        format = new FormataCampos();
        jDateChooserDataInicial.setDate(format.alteraDiaData(format.dataAtual(), -2));
        jDateChooserDataFinal.setDate(format.alteraDiaData(format.dataAtual(), 1));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icones/logo.png")));
        controleDeAcesso();
        psOrdersList = new ArrayList<>();
        jTableOrders.setDefaultRenderer(Object.class, new ConfTabelaSaidasPrestaShop());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupStatusPedido = new javax.swing.ButtonGroup();
        jPanelPesquisa = new javax.swing.JPanel();
        jComboBoxTipoPesquisa = new javax.swing.JComboBox();
        jTextFieldTermoPesquisa = new javax.swing.JTextField();
        jLabelDataInicial = new javax.swing.JLabel();
        jLabelDataFinal = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jRadioButtonPendente = new javax.swing.JRadioButton();
        jRadioButtonCancelado = new javax.swing.JRadioButton();
        jRadioButtonProcessado = new javax.swing.JRadioButton();
        jDateChooserDataInicial = new com.toedter.calendar.JDateChooser();
        jDateChooserDataFinal = new com.toedter.calendar.JDateChooser();
        jRadioButtonTodos = new javax.swing.JRadioButton();
        jRadioButtonEmSeparacao = new javax.swing.JRadioButton();
        jButtonOk = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrders = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pesquisa de Saidas");

        jPanelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jComboBoxTipoPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Referência", "Status do Pedido", "ID" }));
        jComboBoxTipoPesquisa.setSelectedIndex(1);
        jComboBoxTipoPesquisa.setToolTipText("selecione qual o tipo de pesquisa que você deseja fazer");
        jComboBoxTipoPesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoPesquisaItemStateChanged(evt);
            }
        });

        jTextFieldTermoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTermoPesquisaActionPerformed(evt);
            }
        });

        jLabelDataInicial.setText("Data Inicial:");

        jLabelDataFinal.setText("Data Final:");

        jButtonPesquisar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        buttonGroupStatusPedido.add(jRadioButtonPendente);
        jRadioButtonPendente.setSelected(true);
        jRadioButtonPendente.setText("Pendente");
        jRadioButtonPendente.setEnabled(false);

        buttonGroupStatusPedido.add(jRadioButtonCancelado);
        jRadioButtonCancelado.setText("Cancelado");
        jRadioButtonCancelado.setEnabled(false);

        buttonGroupStatusPedido.add(jRadioButtonProcessado);
        jRadioButtonProcessado.setText("Completo");
        jRadioButtonProcessado.setEnabled(false);

        jDateChooserDataInicial.setToolTipText("Insira a data Inicial do filtro");

        jDateChooserDataFinal.setToolTipText("Insira a data final do filtro");

        buttonGroupStatusPedido.add(jRadioButtonTodos);
        jRadioButtonTodos.setText("Todos");

        buttonGroupStatusPedido.add(jRadioButtonEmSeparacao);
        jRadioButtonEmSeparacao.setText("Em Separação");

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTermoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addComponent(jLabelDataInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDataFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonPendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonCancelado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonProcessado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonEmSeparacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTodos)))
                .addGap(0, 332, Short.MAX_VALUE))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTipoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTermoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDataInicial)
                        .addComponent(jLabelDataFinal))
                    .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonPendente)
                        .addComponent(jRadioButtonCancelado)
                        .addComponent(jRadioButtonProcessado)
                        .addComponent(jRadioButtonTodos)
                        .addComponent(jRadioButtonEmSeparacao))
                    .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButtonOk.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ok.png"))); // NOI18N
        jButtonOk.setText("OK!");
        jButtonOk.setEnabled(false);
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTableOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Order", "Referencia", "Cliente", "Pagamento", "Total Desc.", "Total", "Total Frete", "Data Add", "Data Atua."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOrders.getTableHeader().setReorderingAllowed(false);
        jTableOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOrders);
        if (jTableOrders.getColumnModel().getColumnCount() > 0) {
            jTableOrders.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableOrders.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableOrders.getColumnModel().getColumn(2).setPreferredWidth(400);
            jTableOrders.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTableOrders.getColumnModel().getColumn(7).setPreferredWidth(120);
            jTableOrders.getColumnModel().getColumn(8).setPreferredWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancelar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        finalizacao();
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        cancelamento();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        pesquisas();
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldTermoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTermoPesquisaActionPerformed
        pesquisas();
    }//GEN-LAST:event_jTextFieldTermoPesquisaActionPerformed

    private void jComboBoxTipoPesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoPesquisaItemStateChanged
        controleDeAcesso();
    }//GEN-LAST:event_jComboBoxTipoPesquisaItemStateChanged

    private void jTableOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrdersMouseClicked
       jButtonOk.setEnabled(true);
    }//GEN-LAST:event_jTableOrdersMouseClicked

    private void controleDeAcesso() {
        switch (jComboBoxTipoPesquisa.getSelectedIndex()) {
            case 0:
                jRadioButtonCancelado.setEnabled(false);
                jRadioButtonProcessado.setEnabled(false);
                jRadioButtonPendente.setEnabled(false);
                jTextFieldTermoPesquisa.setEnabled(true);
                jDateChooserDataFinal.setEnabled(false);
                jDateChooserDataInicial.setEnabled(false);
                break;
            case 1:
                jRadioButtonCancelado.setEnabled(true);
                jRadioButtonProcessado.setEnabled(true);
                jRadioButtonPendente.setEnabled(true);
                jTextFieldTermoPesquisa.setEnabled(false);
                jDateChooserDataFinal.setEnabled(true);
                jDateChooserDataInicial.setEnabled(true);
                break;
            case 2:
                jRadioButtonCancelado.setEnabled(false);
                jRadioButtonProcessado.setEnabled(false);
                jRadioButtonPendente.setEnabled(false);
                jTextFieldTermoPesquisa.setEnabled(true);
                jDateChooserDataFinal.setEnabled(false);
                jDateChooserDataInicial.setEnabled(false);
                break;
        }

    }

    private void cancelamento() {
        int cancelar = JOptionPane.showConfirmDialog(null, " Deseja realmente cancelar? \n O processo será encerrado!!", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
        if (cancelar == JOptionPane.YES_OPTION) {
            setCancelamento(true);
            dispose();
        }
    }

    public void pesquisas() {
        List<PsOrders> listPsOrders;
        switch (jComboBoxTipoPesquisa.getSelectedIndex()) {
            case 0://por numero do pedido 
                psOrdersList.clear();
                if (!"".equals(jTextFieldTermoPesquisa.getText())) {                   
                    listPsOrders = queryPrestaShop.listPsOrders(jTextFieldTermoPesquisa.getText().trim());                   
                    if (listPsOrders.size() < 1) {
                        JOptionPane.showMessageDialog(null, "Não foi encontrado resultado para essa pesquisa!!! ");
                    } else {//fim if que verifica se existe resultado                       
                        for (PsOrders sales : listPsOrders) {
                            //SalesFlatOrder sa = new PsOrdersJpaController(managerPrestaShop).find(sales.getEntityId());
                            psOrdersList.add(sales);
                        }//fim for
                    }//fim else que verificou lista existente  
                }
                break;
            case 1://por status pedido
                psOrdersList.clear();
                listPsOrders = new ArrayList<>();
                Date dataInicial = jDateChooserDataInicial.getDate();
                Date dataFinal = jDateChooserDataFinal.getDate();
                if (jRadioButtonPendente.isSelected()) {                    
                   List<Integer> list = new ArrayList<>();
                       list.add(1);
                       list.add(2);
                    //  list.add(3);
                        list.add(10);
                      listPsOrders = queryPrestaShop.listPsOrders(list, dataInicial, dataFinal);                   
                } else if (jRadioButtonCancelado.isSelected()) {
                     listPsOrders = queryPrestaShop.listPsOrders(6, dataInicial, dataFinal);                 
                } else if (jRadioButtonProcessado.isSelected()) {
                    listPsOrders = queryPrestaShop.listPsOrders(5, dataInicial, dataFinal);                 
                } else if (jRadioButtonEmSeparacao.isSelected()) {
                    listPsOrders = queryPrestaShop.listPsOrders(3,dataInicial, dataFinal);
                   
                } else {
                    listPsOrders = queryPrestaShop.listPsOrdersUpd(dataInicial, dataFinal);                
                }
                //Date dataInicial = formataCampos.dataBanco(jTextFieldDataInicial.getText());
                //Date dataFinal = formataCampos.dataBanco(jTextFieldDataFinal.getText());

                if (listPsOrders.size() < 1) {
                    JOptionPane.showMessageDialog(null, "Não foi encontrado resultado para essa pesquisa!!! ");
                } else {
                    for (PsOrders sales : listPsOrders) {
                        psOrdersList.add(sales);
                    }//fim for
                }
                break;
            case 2://sem argumento
                psOrdersList.clear();
                listPsOrders = new ArrayList<>();
                if (!"".equals(jTextFieldTermoPesquisa.getText())) {                    
                   listPsOrders = queryPrestaShop.listPsOrders(Integer.valueOf(jTextFieldTermoPesquisa.getText().trim()));
                }
                if (listPsOrders.size() < 1) {
                    JOptionPane.showMessageDialog(null, "Não foi encontrado resultado para essa pesquisa!!! ");
                } else {
                    for (PsOrders sales : listPsOrders) {
                        psOrdersList.add(sales);
                    }//fim for
                }
                break;
            case 3://sem argumento

                break;
            case 4:

                break;
        }
        jButtonOk.setEnabled(false);
        carregaTabelaOrdersl();
    }
    
    private void carregaTabelaOrdersl(){
        DefaultTableModel tab = (DefaultTableModel) jTableOrders.getModel();
        while (jTableOrders.getModel().getRowCount() > 0) {
            ((DefaultTableModel) jTableOrders.getModel()).removeRow(0);
        }
        for (PsOrders e : psOrdersList) {
             //"Id Order", "Referencia", "Cliente", "Pagamento", "Total Desc.", 
             //"Total", "Total Frete", "Data Add", "Data Atua."
            tab.addRow(new Object[]{e.getIdOrder(), e.getReference(), nomeCliente(e.getIdCustomer()),e.getPayment(), format.bigDecimalParaString(e.getTotalDiscountsTaxIncl(), 2) , 
                format.bigDecimalParaString(e.getTotalPaidTaxIncl(), 2), 
                format.bigDecimalParaString(e.getTotalShippingTaxIncl(), 2), 
                format.dataStringDataCompleta(e.getDateAdd(),0), 
                format.dataStringDataCompleta(e.getDateAdd(),0)});
        }   
    }
    
    private String nomeCliente(Integer idCustomer){
        String txt = "";
        for(PsCustomer valor : queryPrestaShop.listCustomer(idCustomer)){                     
                txt = valor.getFirstname() + " " + valor.getLastname();  
                }
        return txt;
    }     

    private void finalizacao() {
        idOrder = jTableOrders.getColumnModel().getColumnIndex("Id Order");
        Integer cod = Integer.valueOf(jTableOrders.getValueAt(jTableOrders.getSelectedRow(), idOrder).toString());
        if (cod != null) {           
            psOrders = new PsOrdersJpaController(Manager.getManagerPrestaShop()).findPsOrders(cod);
            setCancelamento(false);
            dispose();
        } else {
            setCancelamento(true);
            JOptionPane.showMessageDialog(null, "O Código está nullo por favor verifique!!! ");
        }
    }

    public boolean isCancelamento() {
        return cancelamento;
    }

    public void setCancelamento(boolean cancelamento) {
        this.cancelamento = cancelamento;
    }

    public PsOrders getSalesFlatOrder() {
        return psOrders;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidasPrestaShopJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidasPrestaShopJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidasPrestaShopJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidasPrestaShopJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaidasPrestaShopJDialog dialog = new SaidasPrestaShopJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

      private final QueryPrestaShop queryPrestaShop;
    //static EntityManagerFactory managerPrestaShop;
    private boolean cancelamento;
    private PsOrders psOrders;
    private int idOrder;
    private final FormataCampos format;
    private List<PsOrders> psOrdersList;
 
   // private final String shopUrl;
   // private final String key;
   // private ClienteWebService ws;
    // private final String shopUrl = "https://digimacro.com.br";
    //private final String key = "MDUV4W4F7W91BGMVTW5PQYF59N8IVLSC";


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupStatusPedido;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JComboBox jComboBoxTipoPesquisa;
    private com.toedter.calendar.JDateChooser jDateChooserDataFinal;
    private com.toedter.calendar.JDateChooser jDateChooserDataInicial;
    private javax.swing.JLabel jLabelDataFinal;
    private javax.swing.JLabel jLabelDataInicial;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JRadioButton jRadioButtonCancelado;
    private javax.swing.JRadioButton jRadioButtonEmSeparacao;
    private javax.swing.JRadioButton jRadioButtonPendente;
    private javax.swing.JRadioButton jRadioButtonProcessado;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOrders;
    private javax.swing.JTextField jTextFieldTermoPesquisa;
    // End of variables declaration//GEN-END:variables
}
