/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package integrador.separacao;

import entidade.cplus.Moventradaprod;
import entidade.cplus.Moventradaprodserial;
import entidade.cplus.Produto;
import entidade.cplus.Produtocodigo;
import entidade.cplus.Produtoserial;
import entidade.cplus.Unidade;
//import integrador.statico.VariavelStatica;
import acesso.ListagemUsuarioJDialog;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jpa.cplus.MoventradaprodserialJpaController;
import jpa.cplus.ProdutoserialJpaController;
import jpa.cplus.exceptions.IllegalOrphanException;
import jpa.cplus.exceptions.NonexistentEntityException;
import query.cplus.QueryCplus;
import query.integrador.QueryIntegrador;

/**
 *
 * @author leonardo
 */
public class EntradaSerialJDialog extends javax.swing.JDialog {

    /**
     * Creates new form EntradaSerialJDialog
     * @param parent
     * @param modal
     * @param managerCplus1
     * @param managerIntegrador1
     */
    public EntradaSerialJDialog(java.awt.Frame parent, boolean modal, EntityManagerFactory managerCplus1, EntityManagerFactory managerIntegrador1) {
        super(parent, modal);
        initComponents();
        managerCplus = managerCplus1; 
        managerIntegrador = managerIntegrador1;
        queryIntegrador = new QueryIntegrador(managerIntegrador);
        queryCplus = new QueryCplus(managerCplus);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icones/logo.png")));
        listagemUsuarioJDialog = new ListagemUsuarioJDialog(parent, true, managerCplus);
        colunaSerial = jTableSerialDigitado.getColumnModel().getColumnIndex("Serial");
        //var = var1;
        //produto = new ProdutoJpaController(managerCplus).findProduto(movEntradaProd.getCodprod().getCodprod());
       //listCodigo = querySerial.listagemProdutoCodigo(produto.getCodprod());
       //confereQuantidadeDigitada();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSerialDigitado = new javax.swing.JTable();
        jPanelControle = new javax.swing.JPanel();
        jTextFieldSerial = new javax.swing.JTextField();
        jLabelDigiteSerial = new javax.swing.JLabel();
        jLabelQuantidadeFaltando = new javax.swing.JLabel();
        jTextFieldQuantidadeFaltando = new javax.swing.JTextField();
        jButtonGerarSeriais = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonCancelarEntrada = new javax.swing.JButton();
        jPanelInformacoes = new javax.swing.JPanel();
        jButtonExcluirTodosSeriaisDigitados = new javax.swing.JButton();
        jButtonExcluirSerialSelecionado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Processo de Entrada de Seriais");

        jTableSerialDigitado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSerialDigitado.getTableHeader().setReorderingAllowed(false);
        jTableSerialDigitado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSerialDigitadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSerialDigitado);
        if (jTableSerialDigitado.getColumnModel().getColumnCount() > 0) {
            jTableSerialDigitado.getColumnModel().getColumn(0).setMinWidth(100);
            jTableSerialDigitado.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTableSerialDigitado.getColumnModel().getColumn(0).setMaxWidth(500);
        }

        jTextFieldSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerialActionPerformed(evt);
            }
        });

        jLabelDigiteSerial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDigiteSerial.setText("Digite o Serial aqui:");

        jLabelQuantidadeFaltando.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelQuantidadeFaltando.setText("Quantidade Faltando:");

        jTextFieldQuantidadeFaltando.setEditable(false);
        jTextFieldQuantidadeFaltando.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldQuantidadeFaltando.setForeground(new java.awt.Color(204, 51, 0));
        jTextFieldQuantidadeFaltando.setFocusable(false);

        jButtonGerarSeriais.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonGerarSeriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/play.png"))); // NOI18N
        jButtonGerarSeriais.setText("Gerar Seriais");
        jButtonGerarSeriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarSeriaisActionPerformed(evt);
            }
        });

        jButtonGravar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonCancelarEntrada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        jButtonCancelarEntrada.setText("Cancelar Entrada");
        jButtonCancelarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControleLayout = new javax.swing.GroupLayout(jPanelControle);
        jPanelControle.setLayout(jPanelControleLayout);
        jPanelControleLayout.setHorizontalGroup(
            jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDigiteSerial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelQuantidadeFaltando, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSerial)
                            .addGroup(jPanelControleLayout.createSequentialGroup()
                                .addComponent(jTextFieldQuantidadeFaltando, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addComponent(jButtonCancelarEntrada)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGerarSeriais)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelControleLayout.setVerticalGroup(
            jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleLayout.createSequentialGroup()
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDigiteSerial))
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantidadeFaltando)
                            .addComponent(jTextFieldQuantidadeFaltando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGravar)
                            .addComponent(jButtonGerarSeriais)
                            .addComponent(jButtonCancelarEntrada))
                        .addContainerGap())))
        );

        jPanelInformacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Manuten��o"));

        jButtonExcluirTodosSeriaisDigitados.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonExcluirTodosSeriaisDigitados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jButtonExcluirTodosSeriaisDigitados.setText("Excluir Todos Seriais Digitados");
        jButtonExcluirTodosSeriaisDigitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirTodosSeriaisDigitadosActionPerformed(evt);
            }
        });

        jButtonExcluirSerialSelecionado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonExcluirSerialSelecionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jButtonExcluirSerialSelecionado.setText("Excluir Serial Selecionado");
        jButtonExcluirSerialSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirSerialSelecionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInformacoesLayout = new javax.swing.GroupLayout(jPanelInformacoes);
        jPanelInformacoes.setLayout(jPanelInformacoesLayout);
        jPanelInformacoesLayout.setHorizontalGroup(
            jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacoesLayout.createSequentialGroup()
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExcluirTodosSeriaisDigitados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirSerialSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelInformacoesLayout.setVerticalGroup(
            jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacoesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonExcluirSerialSelecionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButtonExcluirTodosSeriaisDigitados))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        if (gravarProdutoSerial() == false) {
            DefaultTableModel tabelaEntradaSerial = (DefaultTableModel) jTableSerialDigitado.getModel();
            int cont = jTableSerialDigitado.getRowCount();
            for (int a = 0; a < cont; a++) {
                tabelaEntradaSerial.removeRow(0);
            }
            dispose();
            setVisible(false);
        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jTextFieldSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerialActionPerformed
       verificaSerial();
       
    }//GEN-LAST:event_jTextFieldSerialActionPerformed

    private void jButtonGerarSeriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarSeriaisActionPerformed
        gerarSeriais();
    }//GEN-LAST:event_jButtonGerarSeriaisActionPerformed

    private void jButtonExcluirSerialSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirSerialSelecionadoActionPerformed
        int cancelar = JOptionPane.showConfirmDialog(null, "DESEJA EXCLUIR A LINHA SELECIONADA??", "Excluir", JOptionPane.YES_NO_CANCEL_OPTION);
        if (cancelar == JOptionPane.YES_NO_OPTION) {//Verifica se ha uma linha selecionada
            excluirSerialSelecionado();
        }
    }//GEN-LAST:event_jButtonExcluirSerialSelecionadoActionPerformed

    private void jTableSerialDigitadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSerialDigitadoMouseClicked
        jButtonExcluirSerialSelecionado.setEnabled(true);
    }//GEN-LAST:event_jTableSerialDigitadoMouseClicked

    private void jButtonExcluirTodosSeriaisDigitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirTodosSeriaisDigitadosActionPerformed
         int cancelar = JOptionPane.showConfirmDialog(null, "CUIDADO!! \n DESEJA REMOVER TODOS OS SERIAIS DA TABELA??", "Excluir", JOptionPane.YES_NO_CANCEL_OPTION);
        if (cancelar == JOptionPane.YES_NO_OPTION) {
            DefaultTableModel tabelaEntradaSerial = (DefaultTableModel) jTableSerialDigitado.getModel();
            int cont = jTableSerialDigitado.getRowCount();
            for (int a = 0; a < cont; a++) {
                tabelaEntradaSerial.removeRow(0);
            }            
            confereQuantidadeDigitada();
        }
    }//GEN-LAST:event_jButtonExcluirTodosSeriaisDigitadosActionPerformed

    private void jButtonCancelarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarEntradaActionPerformed
        int cancelar = JOptionPane.showConfirmDialog(null, "CUIDADO!! \n SER� CANCELADO A ENTRADA DE SERIAIS DESSE PRODUTO", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
        if (cancelar == JOptionPane.YES_NO_OPTION) {
             dispose();
       setVisible(false);
        }
    }//GEN-LAST:event_jButtonCancelarEntradaActionPerformed

    private void excluirSerialSelecionado(){
        DefaultTableModel tabelaEntradaSerial = (DefaultTableModel) jTableSerialDigitado.getModel();
        tabelaEntradaSerial.removeRow(jTableSerialDigitado.getSelectedRow());
        jButtonExcluirSerialSelecionado.setEnabled(false);
        confereQuantidadeDigitada();
    }
    
    private void gerarSeriais() {
        gerarSerialPorData = new SimpleDateFormat("ddMMyyHHmmss").format(new Date());
        gerarSerialPorData = gerarSerialPorData + "001";
        int quantidadeEntrada = quantidadeEntrada(movEntradaProd);
        long cont = Long.parseLong(gerarSerialPorData);
        DefaultTableModel tabelaEntradaSerial = (DefaultTableModel) jTableSerialDigitado.getModel();
        for (int increment = 0; increment < quantidadeEntrada; increment++) {
            cont++;
            List<Produtoserial> produtoSerial = queryCplus.pesquisaSerialExato(String.valueOf(cont));
            if (produtoSerial.isEmpty()) {
                jTableSerialDigitado.clearSelection(); //Tira linha selecionada
                tabelaEntradaSerial.addRow(new Object[]{String.valueOf(cont)});
                jTableSerialDigitado.setRowSelectionInterval(jTableSerialDigitado.getRowCount() - 1, jTableSerialDigitado.getRowCount() - 1);//seleciona ultima linha
            } else {
                increment --;
                tocarSomErro();
                JOptionPane.showMessageDialog(null, "O Serial digitado j� est� cadastrado!!! \n" + produtoSerial.size() + " Resultados encontrados");
                this.listagemUsuarioJDialog.setVisible(true);
            }
        }
        confereQuantidadeDigitada();
        tocarSomFinalizado();
    }
    
    public void confereQuantidadeDigitada(){           
        if(jTableSerialDigitado.getRowCount() == quantidadeEntrada(movEntradaProd)){
            jButtonGravar.setEnabled(true);
            jTextFieldSerial.setEnabled(false);
            jTextFieldSerial.setText("");
            jButtonGerarSeriais.setEnabled(false);
            jTextFieldQuantidadeFaltando.setText("0");
            jButtonExcluirTodosSeriaisDigitados.setEnabled(true);
        }else{
            int quantFaltando = quantidadeEntrada(movEntradaProd) - jTableSerialDigitado.getRowCount();
            jTextFieldQuantidadeFaltando.setText(String.valueOf(quantFaltando));           
            if(jTableSerialDigitado.getRowCount() < 1){
                jButtonGerarSeriais.setEnabled(true);
                jButtonExcluirSerialSelecionado.setEnabled(false);
                jButtonExcluirTodosSeriaisDigitados.setEnabled(false);
            }else{
                jButtonExcluirTodosSeriaisDigitados.setEnabled(true);
                jButtonGerarSeriais.setEnabled(false);
            }
            jButtonGravar.setEnabled(false);
            jTextFieldSerial.setEnabled(true);
            jTextFieldSerial.selectAll();
            jTextFieldSerial.requestFocus();
        }
    }
    
    private boolean gravarProdutoSerial() {      
        boolean condicao = false;
        int contTabela = jTableSerialDigitado.getRowCount();
        int contProdSerial = queryCplus.incrementProdutoSerial();
        int contMovProdSerial = queryCplus.incrementMovEntradaProdSerial();
        for (int cont = 0; cont < contTabela; cont++) {//Percore todos os registros da tabela
            contProdSerial++;
            contMovProdSerial++;
            jTableSerialDigitado.setRowSelectionInterval(cont, cont);
            Produtoserial produtoSerial = new Produtoserial();//instancia classe
            produtoSerial.setCodprod(produto);
            produtoSerial.setSerial(jTableSerialDigitado.getValueAt(cont, colunaSerial).toString());//pega valor de jTable Serial
            produtoSerial.setCodprodutoserial(String.format("%09d", contProdSerial));
            produtoSerial.setDataentrada(new Date(System.currentTimeMillis()));
            try {
                new ProdutoserialJpaController(managerCplus).create(produtoSerial);//Cria objeto no banco de dados
                if(gravarMovProdSerial(new ProdutoserialJpaController(managerCplus).findProdutoserial(produtoSerial.getCodprodutoserial()), contMovProdSerial)){
                    condicao = true;
                }
            } catch (Exception ex) {
                tocarSomErro();
                JOptionPane.showMessageDialog(null, "\n Erro ao gravar produto Serial.\n " + ex);
                condicao = true;
            }
            if(condicao){
                excluirEntradaSerialBanco();
                JOptionPane.showMessageDialog(null, "OS REGISTROS FORAM EXCLUIDOS TENTE NOVAMENTE!!" );
                break;
            }
        }
        jButtonGravar.setEnabled(false);
        return condicao;
    }
    
    private boolean gravarMovProdSerial(Produtoserial produtoSerial, int cont) {
        boolean condicao = false;
        Moventradaprodserial movEntradaSerial = new Moventradaprodserial();                
        movEntradaSerial.setCodprodutoserial(produtoSerial);                           
        movEntradaSerial.setCodmoveprod(movEntradaProd);
        movEntradaSerial.setCodmoventradaprodserial(String.format("%09d", cont));
        try {
            new MoventradaprodserialJpaController(managerCplus).create(movEntradaSerial);  
        } catch (Exception ex) {
            tocarSomErro();
            JOptionPane.showMessageDialog(null, "\n Erro ao gravar Entrada Serial.\n " + ex);
            condicao = true;
        }
        return condicao;
    }
    
    private void excluirEntradaSerialBanco(){
        List<Moventradaprodserial> listMovProdSerial = queryCplus.listagemSerialEntradaProd(movEntradaProd.getCodmoveprod());
        for(Moventradaprodserial movProdSerial : listMovProdSerial){
            try {
                new MoventradaprodserialJpaController(managerCplus).destroy(movProdSerial.getCodmoventradaprodserial());
            } catch (NonexistentEntityException ex) {
                tocarSomErro();
                JOptionPane.showMessageDialog(null, "\n Erro ao Excluir Entrada Serial.\n " + ex);
            }
            try {
                new ProdutoserialJpaController(managerCplus).destroy(movProdSerial.getCodprodutoserial().getCodprodutoserial());
            } catch (IllegalOrphanException | NonexistentEntityException ex) {
                tocarSomErro();
                JOptionPane.showMessageDialog(null, "\n Erro ao Excluir Produto Serial.\n " + ex);
            }
        }
        jButtonGravar.setEnabled(true);
    }
    
    private void verificaSerial() {
        String textoDigitado = jTextFieldSerial.getText().toUpperCase().trim();
        List<Produtoserial> produtoSerial = queryCplus.pesquisaSerialExato(textoDigitado);
        if (produtoSerial.isEmpty()) {//if que verifica se o serial j� est� no banco
            if (serialCadastroEntrada(textoDigitado)) {//if que verifica se o serial j� est� na tabela
                if (verificaQuantidade()) {//if que verifica se a quantidade digitada foi exedida
                    if (verificaCodigos(textoDigitado)) {
                        DefaultTableModel tabelaEntradaSerial = (DefaultTableModel) jTableSerialDigitado.getModel();
                        jTableSerialDigitado.clearSelection(); //Tira linha selecionada
                        tabelaEntradaSerial.addRow(new Object[]{textoDigitado});
                        jTableSerialDigitado.setRowSelectionInterval(jTableSerialDigitado.getRowCount() - 1, jTableSerialDigitado.getRowCount() - 1);//seleciona ultima linha                        
                    } else {
                        tocarSomErro();
                        JOptionPane.showMessageDialog(null, "Não pode ser EAN ou outros Códigos!!!");
                        this.listagemUsuarioJDialog.setVisible(true);
                    }
                } else {
                    tocarSomErro();
                    JOptionPane.showMessageDialog(null, "A Entrada de Serial desse Produto já está completa!!!!!");
                    this.listagemUsuarioJDialog.setVisible(true);
                }
            } else {
                tocarSomErro();
                JOptionPane.showMessageDialog(null, "O Serial já está na tabela!!! \n Serial: " + textoDigitado);
                this.listagemUsuarioJDialog.setVisible(true);
            }
        } else {//else que verifica se ha serial cadastrado
            tocarSomErro();
            JOptionPane.showMessageDialog(null, "O Serial digitado já está cadastrado!!! \n" + produtoSerial.size() + " Resultados encontrados");
            this.listagemUsuarioJDialog.setVisible(true);
        }
        confereQuantidadeDigitada();
    }
    
    private boolean verificaCodigos(String textoDigitado) {
        boolean condicao = true;
        if (produto.getCodigo() == null ? textoDigitado == null : produto.getCodigo().equals(textoDigitado)) {
            condicao = false;
        } else {
            for (Produtocodigo cod : listCodigo) {
                if (cod.getCodigo() == null ? textoDigitado == null : cod.getCodigo().equals(textoDigitado)) {
                    condicao = false;
                }
            }
        }
        return condicao;
    }
    
    private boolean verificaQuantidade(){
        boolean condicao = true;   
       // int cont = jTableSerialDigitado.getRowCount();
        if(jTableSerialDigitado.getRowCount() > quantidadeEntrada(movEntradaProd)){           
            condicao = false;           
        }        
        return condicao;      
    }
    
    private boolean serialCadastroEntrada(String textoDigitado) {
        boolean condicao = true;
        int totalLinhaSerial = jTableSerialDigitado.getRowCount();
        String serialTabela;
        colunaSerial = jTableSerialDigitado.getColumnModel().getColumnIndex("Serial");
        for (int linhaSerial = 0; linhaSerial < totalLinhaSerial; linhaSerial++) {           
            serialTabela = jTableSerialDigitado.getValueAt(linhaSerial, colunaSerial).toString();
            if (serialTabela.equals(textoDigitado)) {
                jTableSerialDigitado.setRowSelectionInterval(linhaSerial, linhaSerial);
                condicao = false;              
                break;
            }
        }
        return condicao;
    }
    
    private int quantidadeEntrada(Moventradaprod prodEnt) {
        int quantidade = prodEnt.getQuantidade().intValue();
        List<Unidade> listUn = queryCplus.resultPorUnidadeProduto(prodEnt.getCodprod().getUnidade());
        for (Unidade un : listUn) {
            if (un.getFatorconversao().intValue() > 1) {
                quantidade = quantidade / un.getFatorconversao().intValue();
            }
        }
        quantidade = quantidade - queryCplus.listagemSerialEntradaProd(prodEnt.getCodmoveprod()).size();
        return quantidade;
    }
    
    private void tocarSomErro() {
        String path = queryIntegrador.valorConfiguracao("caminho_ARQUIVO_AUDIO_ERRO");
        File mp3File = new File(path);
        ReproduzirAudio musica = new ReproduzirAudio(mp3File);
        musica.play();
    }

    private void tocarSomFinalizado() {
        String path = queryIntegrador.valorConfiguracao("caminho_ARQUIVO_AUDIO_FINALIZADO");
        File mp3File = new File(path);
        ReproduzirAudio musica = new ReproduzirAudio(mp3File);
        musica.play();
    }
       
    public void setMovEntradaProd(Moventradaprod movEntradaProd) {
        this.movEntradaProd = movEntradaProd;
    }

    public void setListCodigo(List<Produtocodigo> listCodigo) {
        this.listCodigo = listCodigo;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EntradaSerialJDialog dialog = new EntradaSerialJDialog(new javax.swing.JFrame(), true, managerCplus, managerIntegrador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

     QueryCplus queryCplus;
     QueryIntegrador queryIntegrador;
    static EntityManagerFactory managerCplus;
    static EntityManagerFactory managerIntegrador;
    private Moventradaprod movEntradaProd;
    ListagemUsuarioJDialog listagemUsuarioJDialog;
    private int colunaSerial;
    private List<Produtocodigo> listCodigo;
    private Produto produto;
    private String gerarSerialPorData;
    //static VariavelStatica var;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarEntrada;
    private javax.swing.JButton jButtonExcluirSerialSelecionado;
    private javax.swing.JButton jButtonExcluirTodosSeriaisDigitados;
    private javax.swing.JButton jButtonGerarSeriais;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JLabel jLabelDigiteSerial;
    private javax.swing.JLabel jLabelQuantidadeFaltando;
    private javax.swing.JPanel jPanelControle;
    private javax.swing.JPanel jPanelInformacoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSerialDigitado;
    private javax.swing.JTextField jTextFieldQuantidadeFaltando;
    private javax.swing.JTextField jTextFieldSerial;
    // End of variables declaration//GEN-END:variables
}
