/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integrador.separacao;

import entidade.cplus.Localizacao;
import entidade.cplus.Moventrada;
import entidade.cplus.Moventradaprod;
import entidade.cplus.Produto;
import entidade.cplus.Produtoestoque;
import entidade.cplus.Unidade;
import janela.cplus.ListagemEntradasJDialog;
import janela.cplus.ListagemLocalizacaoJDialog;
import janela.cplus.ListagemProdutoJDialog;
import java.awt.Color;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import jpa.cplus.MoventradaprodJpaController;
import query.cplus.QueryCplus;
import query.integrador.QueryIntegrador;

/**
 *
 * @author leonardo
 */
public class EntradaSerialJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EntradaSerialJFrame
     *
     * @param managerCplus1
     * @param managerIntegrador1
     */
    public EntradaSerialJFrame(EntityManagerFactory managerCplus1, EntityManagerFactory managerIntegrador1) {
        initComponents();
        managerCplus = managerCplus1;
        managerIntegrador = managerIntegrador1;
        this.listagemEntradasJDialog = new ListagemEntradasJDialog(this, true, managerCplus);
        //this.listagemUsuarioJDialog = new ListagemUsuarioJDialog(this, true, managerCplus);
        this.entradaSerialJDialog = new EntradaSerialJDialog(this, true, managerCplus, managerIntegrador1);
        this.listagemSerialEntradaJDialog = new ListagemSerialEntradaJDialog(this, true, managerCplus, managerIntegrador);
        //querySerial = new QuerySerial(managerCplus);
        queryIntegrador = new QueryIntegrador(managerIntegrador);
        queryCplus = new QueryCplus(managerCplus);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icones/logo.png")));
        colunaCodMovProd = jTableEntradaProd.getColumnModel().getColumnIndex("Codmoveprod");
        this.listagemLocalizacaoJDialog = new ListagemLocalizacaoJDialog(this, true, managerCplus);
        this.listagemProdutoJDialog = new ListagemProdutoJDialog(this, true, managerCplus);

        //new RenderPreco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEntradaProd = new javax.swing.JTable();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonPesquisaEntrada = new javax.swing.JButton();
        jButtonListaSerialProduto = new javax.swing.JToggleButton();
        jButtonListaSerialEntrada = new javax.swing.JButton();
        jButtonEntradaDeSeriais = new javax.swing.JButton();
        jLabelStatusEntrada = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jButtonEditarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seriais de Entrada");

        jTableEntradaProd.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jTableEntradaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Produto", "Quantidade", "Completo", "Setor", "Estoque Atual", "Codmoveprod"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEntradaProd.setColumnSelectionAllowed(true);
        jTableEntradaProd.setRowHeight(25);
        jTableEntradaProd.getTableHeader().setReorderingAllowed(false);
        jTableEntradaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEntradaProdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEntradaProd);
        jTableEntradaProd.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableEntradaProd.getColumnModel().getColumnCount() > 0) {
            jTableEntradaProd.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableEntradaProd.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Painel"));

        jButtonPesquisaEntrada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonPesquisaEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jButtonPesquisaEntrada.setText("Pesquisar Entrada");
        jButtonPesquisaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaEntradaActionPerformed(evt);
            }
        });

        jButtonListaSerialProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonListaSerialProduto.setText("Lista Seriais do Produto");
        jButtonListaSerialProduto.setEnabled(false);
        jButtonListaSerialProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaSerialProdutoActionPerformed(evt);
            }
        });

        jButtonListaSerialEntrada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonListaSerialEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/info.png"))); // NOI18N
        jButtonListaSerialEntrada.setText("Lista Seriais Entrada");
        jButtonListaSerialEntrada.setEnabled(false);
        jButtonListaSerialEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListaSerialEntradaActionPerformed(evt);
            }
        });

        jButtonEntradaDeSeriais.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEntradaDeSeriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        jButtonEntradaDeSeriais.setText("Entrada de Seriais");
        jButtonEntradaDeSeriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntradaDeSeriaisActionPerformed(evt);
            }
        });

        jLabelStatusEntrada.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jButtonFechar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/stop.png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jButtonEditarProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Edit.png"))); // NOI18N
        jButtonEditarProduto.setText("Editar Produto");
        jButtonEditarProduto.setEnabled(false);
        jButtonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonListaSerialProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jButtonPesquisaEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonListaSerialEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jButtonEntradaDeSeriais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabelStatusEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 417, Short.MAX_VALUE)
                        .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFechar)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStatusEntrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonPesquisaEntrada)
                                .addComponent(jButtonEntradaDeSeriais)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonListaSerialProduto)
                            .addComponent(jButtonListaSerialEntrada)
                            .addComponent(jButtonEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaEntradaActionPerformed
        pesquisarEntrada();
    }//GEN-LAST:event_jButtonPesquisaEntradaActionPerformed

    private void jButtonEntradaDeSeriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntradaDeSeriaisActionPerformed
        if (jTableEntradaProd.getRowCount() > 0 && jTableEntradaProd.getSelectedRow() != -1) {
            colunaCodMovProd = jTableEntradaProd.getColumnModel().getColumnIndex("Codmoveprod");
            String codMovProd = jTableEntradaProd.getValueAt(jTableEntradaProd.getSelectedRow(), colunaCodMovProd).toString();
            movEntradaProd = new MoventradaprodJpaController(managerCplus).findMoventradaprod(codMovProd);
            this.entradaSerialJDialog.setProduto(movEntradaProd.getCodprod());
            this.entradaSerialJDialog.setListCodigo(queryCplus.listagemProdutoCodigo(movEntradaProd.getCodprod().getCodprod()));
            this.entradaSerialJDialog.setMovEntradaProd(movEntradaProd);
            this.entradaSerialJDialog.confereQuantidadeDigitada();
            this.entradaSerialJDialog.setVisible(true);
            verificaEntradaCompleta();
            verificaEntradaProdutoCompleta();
            carregarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_jButtonEntradaDeSeriaisActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // removeConfiguracao();
        dispose();
        setVisible(false);
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonListaSerialEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaSerialEntradaActionPerformed
        if (jTableEntradaProd.getRowCount() > 0) {
            this.listagemSerialEntradaJDialog.setMovEntrada(movEntrada);
            this.listagemSerialEntradaJDialog.setVisible(true);
            carregarTabela();
        }
    }//GEN-LAST:event_jButtonListaSerialEntradaActionPerformed

    private void jTableEntradaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEntradaProdMouseClicked
        verificaEntradaProdutoCompleta();
        jButtonListaSerialProduto.setEnabled(true);
        jButtonEditarProduto.setEnabled(true);
    }//GEN-LAST:event_jTableEntradaProdMouseClicked

    private void jButtonListaSerialProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListaSerialProdutoActionPerformed
        if (jTableEntradaProd.getRowCount() > 0) {
            colunaCodMovProd = jTableEntradaProd.getColumnModel().getColumnIndex("Codmoveprod");
            String codMovProd = jTableEntradaProd.getValueAt(jTableEntradaProd.getSelectedRow(), colunaCodMovProd).toString();
            this.listagemSerialEntradaJDialog.setMovEntradaProd(codMovProd);
            this.listagemSerialEntradaJDialog.setVisible(true);

        }
    }//GEN-LAST:event_jButtonListaSerialProdutoActionPerformed

    private void jButtonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProdutoActionPerformed

        /**
         * this.listagemLocalizacaoJDialog.setVisible(true); if
         * (this.listagemLocalizacaoJDialog.isCancelamento() == false) {
         * for(Produto p :
         * queryCplus.listProduto(movEntradaProd.getCodprod().getCodprod())){
         * try {
         * p.setCodloc(this.listagemLocalizacaoJDialog.getLocalizacao().getCodloc());
         * new ProdutoJpaController(managerCplus).edit(p);
         * jButtonEditarSetorEstoque.setEnabled(false); carregarTabela(); }
         * catch (jpa.cplus.exceptions.NonexistentEntityException ex) {
         * JOptionPane.showMessageDialog(null, "Houve um ero ao editar produto!
         * \n"+ex); } catch (Exception ex) { JOptionPane.showMessageDialog(null,
         * "Houve um ero ao editar produto! \n"+ex); } } }
         */
        if (jTableEntradaProd.getRowCount() > 0 && jTableEntradaProd.getSelectedRow() != -1) {
            colunaCodMovProd = jTableEntradaProd.getColumnModel().getColumnIndex("Codmoveprod");
            String codMovProd = jTableEntradaProd.getValueAt(jTableEntradaProd.getSelectedRow(), colunaCodMovProd).toString();
            movEntradaProd = new MoventradaprodJpaController(managerCplus).findMoventradaprod(codMovProd);
            this.listagemProdutoJDialog.setTermoPesquisa(movEntradaProd.getCodprod().getCodigo());
            this.listagemProdutoJDialog.setVisible(true);
            jButtonEditarProduto.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_jButtonEditarProdutoActionPerformed

    private void verificaEntradaProdutoCompleta() {
        //jButtonEntradaDeSeriais.setEnabled(false);
        //   if (verificaEntradaAberta()) {
        colunaCodMovProd = jTableEntradaProd.getColumnModel().getColumnIndex("Codmoveprod");
        String codMovProd = jTableEntradaProd.getValueAt(jTableEntradaProd.getSelectedRow(), colunaCodMovProd).toString();
        movEntradaProd = new MoventradaprodJpaController(managerCplus).findMoventradaprod(codMovProd);
        if (movEntradaProd.getCodmoveprod() != null || !"".equals(movEntradaProd.getCodmoveprod())) {
            int completo = queryIntegrador.listPorEntradaProd(movEntradaProd.getCodmoveprod()).size();
            if (quanPacote(movEntradaProd) != completo) {
                //jButtonEntradaDeSeriais.setEnabled(true);
            } else {
                //jButtonEntradaDeSeriais.setEnabled(false);
                for (int cont = 0; cont < jTableEntradaProd.getRowCount(); cont++) {
                    if (movEntradaProd.getCodmoveprod() == jTableEntradaProd.getValueAt(cont, colunaCodMovProd)) {
                        jTableEntradaProd.setRowSelectionInterval(cont, cont);
                    }
                }
            }
        }
        //  }
    }

    public void carregarTabela() {
        List<Moventradaprod> moEntradaProduto = queryCplus.listagemMovEntradaProdPorEntrada(movEntrada.getCodmoventr());
        DefaultTableModel tab = (DefaultTableModel) jTableEntradaProd.getModel();
        while (jTableEntradaProd.getModel().getRowCount() > 0) {
            ((DefaultTableModel) jTableEntradaProd.getModel()).removeRow(0);
        }
        for (Moventradaprod e : moEntradaProduto) {
            int comp = queryIntegrador.listPorEntradaProd(e.getCodmoveprod()).size();
            tab.addRow(new Object[]{e.getCodprod().getCodigo(), e.getCodprod().getNomeprod(), quanPacote(e), comp, setor(e.getCodprod()), EstoqueCplus(e.getCodprod().getCodprod()), e.getCodmoveprod()});
        }
        colorirLinha();
    }

    private String setor(Produto codProd) {
        String text = "";
        for (Localizacao loc : queryCplus.listLocalizacao(codProd.getCodloc())) {
            text = loc.getDescricao();
        }
        return text;
    }

    private Integer EstoqueCplus(String codProd) {
        BigDecimal estoque = BigDecimal.ZERO;
        List<Produtoestoque> listEsroque = new QueryCplus(managerCplus).listEstoquesPorProd(codProd);
        for (Produtoestoque est : listEsroque) {
            estoque = est.getEstatu().subtract(est.getReservadoorcamento().subtract(est.getReservadoos()));
        }
        return estoque.intValue();
    }

    private void pesquisarEntrada() {
        //moventradaprodList.clear();
        jButtonListaSerialProduto.setEnabled(false);
        this.listagemEntradasJDialog.setVisible(true);
        if (this.listagemEntradasJDialog.isCancelamento() == false) {
            movEntrada = this.listagemEntradasJDialog.getMovEntrada();
            carregarTabela();
            verificaEntradaCompleta();
            jButtonListaSerialEntrada.setEnabled(true);
        }//fim if pesquisa entrada cancelada
    }

    private void verificaEntradaCompleta() {
        int entSerial = 0;
        List<Moventradaprod> listProdEntrada = queryCplus.listagemMovEntradaProdPorEntrada(movEntrada.getCodmoventr());
        int totalProdutos = 0;
        for (Moventradaprod prod : listProdEntrada) {
            totalProdutos = totalProdutos + (quanPacote(prod));
            entSerial = entSerial + queryIntegrador.listPorEntradaProd(prod.getCodmoveprod()).size();
        }
        if (entSerial == totalProdutos) {
            jLabelStatusEntrada.setForeground(Color.GREEN);
            jLabelStatusEntrada.setText("Entrada de Serial Completa");
            //jButtonEntradaDeSeriais.setEnabled(false);
        } else {
//            insereConfiguracaoParaGravacaoEntrada();
            jLabelStatusEntrada.setForeground(Color.RED);
            jLabelStatusEntrada.setText("Entrada de Serial Incompleta");
            //jButtonEntradaDeSeriais.setEnabled(true);
        }
    }

    private String retornaIpLocal() {
        InetAddress ia = null;
        try {
            ia = InetAddress.getLocalHost();
        } catch (UnknownHostException e) {
            JOptionPane.showMessageDialog(null, "HOUVE UM ERRO AO OBTER IP LOCAL, Verifique!! \n" + e, "Erro Entrada", JOptionPane.ERROR_MESSAGE);
        }
        return "entrada_serial_" + ia.getHostAddress() + "_" + ia.getHostName();
    }

    private int quanPacote(Moventradaprod prodEnt) {
        int quantidade = prodEnt.getQuantidade().intValue();
        List<Unidade> listUn = queryCplus.resultPorUnidadeProduto(prodEnt.getCodprod().getUnidade());
        for (Unidade un : listUn) {
            if (un.getFatorconversao().intValue() > 1) {
                quantidade = quantidade / un.getFatorconversao().intValue();
            }
        }
        return quantidade;
    }

    private void colorirLinha() {
        TableCellRenderer renderer = new ColorirTabelaEntradaSerial();
        for (int c = 0; c < jTableEntradaProd.getColumnCount(); c++) {
            jTableEntradaProd.setDefaultRenderer(jTableEntradaProd.getColumnClass(c), renderer);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaSerialJFrame(managerCplus, managerIntegrador).setVisible(true);
            }
        });
    }

    //QuerySerial querySerial;
    private static EntityManagerFactory managerCplus;
    private final ListagemEntradasJDialog listagemEntradasJDialog;
    private final ListagemSerialEntradaJDialog listagemSerialEntradaJDialog;
    private final EntradaSerialJDialog entradaSerialJDialog;
    private static EntityManagerFactory managerIntegrador;
    private final QueryCplus queryCplus;
    private final QueryIntegrador queryIntegrador;
    private Moventrada movEntrada;
    private Moventradaprod movEntradaProd;
    private int colunaCodMovProd;
    private final ListagemLocalizacaoJDialog listagemLocalizacaoJDialog;
    private final ListagemProdutoJDialog listagemProdutoJDialog;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditarProduto;
    private javax.swing.JButton jButtonEntradaDeSeriais;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonListaSerialEntrada;
    private javax.swing.JToggleButton jButtonListaSerialProduto;
    private javax.swing.JButton jButtonPesquisaEntrada;
    private javax.swing.JLabel jLabelStatusEntrada;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEntradaProd;
    // End of variables declaration//GEN-END:variables
}
