/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integrador.separacao;

import acesso.ListagemUsuarioJDialog;
import entidade.cplus.Localizacao;
import entidade.cplus.Moventradaprod;
import entidade.cplus.Produto;
import entidade.cplus.Produtocodigo;
import entidade.cplus.Produtoestoque;
import entidade.cplus.Unidade;
import entidade.integrador.EntradaSerial;
import entidade.integrador.SerialProduto;
import integrador.relatorio.ImprimeRelatorio;
import janela.cplus.ListagemProdutoJDialog;
import java.awt.Toolkit;
import java.io.File;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jpa.integrador.EntradaSerialJpaController;
import jpa.integrador.SerialProdutoJpaController;
import jpa.integrador.exceptions.NonexistentEntityException;
import prestashop.ConfiguracaoNoBD;
import prestashop.Manager;
import query.cplus.QueryCplus;
import query.integrador.QueryIntegrador;

/**
 *
 * @author leonardo
 */
public class EntradaSerialJDialog extends javax.swing.JDialog {

    /**
     * Creates new form EntradaSerialJDialog
     *
     * @param parent
     * @param modal
     */
    public EntradaSerialJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();       
        queryIntegrador = new QueryIntegrador();
        queryCplus = new QueryCplus();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icones/logo.png")));
        listagemUsuarioJDialog = new ListagemUsuarioJDialog(parent, true);
        colunaSerial = jTableSerialDigitado.getColumnModel().getColumnIndex("Serial");
        //this.listagemLocalizacaoJDialog = new ListagemLocalizacaoJDialog(parent, true, Manager.getManagerCplus());
        this.listagemProdutoJDialog = new ListagemProdutoJDialog(parent, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSerialDigitado = new javax.swing.JTable();
        jPanelControle = new javax.swing.JPanel();
        jTextFieldSerial = new javax.swing.JTextField();
        jLabelDigiteSerial = new javax.swing.JLabel();
        jLabelQuantidadeFaltando = new javax.swing.JLabel();
        jTextFieldQuantidadeFaltando = new javax.swing.JTextField();
        jButtonGerarSeriais = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonCancelarEntrada = new javax.swing.JButton();
        jLabelEstoqueTotal = new javax.swing.JLabel();
        jTextFieldEstoqueCplus = new javax.swing.JTextField();
        jLabelSetor = new javax.swing.JLabel();
        jTextFieldSetor = new javax.swing.JTextField();
        jPanelInformacoes = new javax.swing.JPanel();
        jButtonExcluirSerialSelecionado = new javax.swing.JButton();
        jButtonImprimirEtiqueta = new javax.swing.JButton();
        jTextFieldPrimeiroSerial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumeroDeItens = new javax.swing.JTextField();
        jToggleButtonEntradaSequencial = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Processo de Entrada de Seriais");

        jTableSerialDigitado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSerialDigitado.getTableHeader().setReorderingAllowed(false);
        jTableSerialDigitado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSerialDigitadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSerialDigitado);
        if (jTableSerialDigitado.getColumnModel().getColumnCount() > 0) {
            jTableSerialDigitado.getColumnModel().getColumn(0).setMinWidth(100);
            jTableSerialDigitado.getColumnModel().getColumn(0).setPreferredWidth(250);
            jTableSerialDigitado.getColumnModel().getColumn(0).setMaxWidth(500);
        }

        jTextFieldSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerialActionPerformed(evt);
            }
        });

        jLabelDigiteSerial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDigiteSerial.setText("Digite o Serial aqui:");

        jLabelQuantidadeFaltando.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelQuantidadeFaltando.setText("Quantidade Faltando:");

        jTextFieldQuantidadeFaltando.setEditable(false);
        jTextFieldQuantidadeFaltando.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldQuantidadeFaltando.setForeground(new java.awt.Color(204, 51, 0));
        jTextFieldQuantidadeFaltando.setFocusable(false);

        jButtonGerarSeriais.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonGerarSeriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/play.png"))); // NOI18N
        jButtonGerarSeriais.setText("Gerar Seriais");
        jButtonGerarSeriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarSeriaisActionPerformed(evt);
            }
        });

        jButtonGravar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonCancelarEntrada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelarEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        jButtonCancelarEntrada.setText("Cancelar Entrada");
        jButtonCancelarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarEntradaActionPerformed(evt);
            }
        });

        jLabelEstoqueTotal.setText("Estoque Total:");

        jTextFieldEstoqueCplus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldEstoqueCplus.setEnabled(false);

        jLabelSetor.setText("Setor:");

        jTextFieldSetor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldSetor.setEnabled(false);

        javax.swing.GroupLayout jPanelControleLayout = new javax.swing.GroupLayout(jPanelControle);
        jPanelControle.setLayout(jPanelControleLayout);
        jPanelControleLayout.setHorizontalGroup(
            jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelDigiteSerial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelQuantidadeFaltando, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSerial)
                            .addGroup(jPanelControleLayout.createSequentialGroup()
                                .addComponent(jTextFieldQuantidadeFaltando, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelSetor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabelEstoqueTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEstoqueCplus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addComponent(jButtonCancelarEntrada)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonGerarSeriais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelControleLayout.setVerticalGroup(
            jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControleLayout.createSequentialGroup()
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDigiteSerial))
                .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQuantidadeFaltando)
                            .addComponent(jTextFieldQuantidadeFaltando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControleLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEstoqueCplus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEstoqueTotal)
                            .addComponent(jTextFieldSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSetor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGravar)
                            .addComponent(jButtonGerarSeriais)
                            .addComponent(jButtonCancelarEntrada))
                        .addContainerGap())))
        );

        jPanelInformacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Manutenção"));

        jButtonExcluirSerialSelecionado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonExcluirSerialSelecionado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jButtonExcluirSerialSelecionado.setText("Excluir Serial Selecionado");
        jButtonExcluirSerialSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirSerialSelecionadoActionPerformed(evt);
            }
        });

        jButtonImprimirEtiqueta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonImprimirEtiqueta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/imprimir.png"))); // NOI18N
        jButtonImprimirEtiqueta.setText("Imprimir Seriais");
        jButtonImprimirEtiqueta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirEtiquetaActionPerformed(evt);
            }
        });

        jLabel1.setText("Entrada por Sequencia");

        jLabel2.setText("Primeiro Serial:");

        jLabel3.setText("Numero de Itens:");

        jToggleButtonEntradaSequencial.setText("Entrada Sequencial");
        jToggleButtonEntradaSequencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEntradaSequencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInformacoesLayout = new javax.swing.GroupLayout(jPanelInformacoes);
        jPanelInformacoes.setLayout(jPanelInformacoesLayout);
        jPanelInformacoesLayout.setHorizontalGroup(
            jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonImprimirEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirSerialSelecionado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPrimeiroSerial, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNumeroDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                        .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jToggleButtonEntradaSequencial))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInformacoesLayout.setVerticalGroup(
            jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonImprimirEtiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluirSerialSelecionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrimeiroSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNumeroDeItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonEntradaSequencial)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        dispose();
        setVisible(false);

    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jTextFieldSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerialActionPerformed
        verificaSerial();

    }//GEN-LAST:event_jTextFieldSerialActionPerformed

    private void jButtonGerarSeriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarSeriaisActionPerformed
        gerarSeriais();
    }//GEN-LAST:event_jButtonGerarSeriaisActionPerformed

    private void jButtonExcluirSerialSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirSerialSelecionadoActionPerformed
        int cancelar = JOptionPane.showConfirmDialog(null, "DESEJA EXCLUIR A LINHA SELECIONADA??", "Excluir", JOptionPane.YES_NO_CANCEL_OPTION);
        if (cancelar == JOptionPane.YES_NO_OPTION) {//Verifica se ha uma linha selecionada
            excluirSerialSelecionado();
        }
    }//GEN-LAST:event_jButtonExcluirSerialSelecionadoActionPerformed

    private void jTableSerialDigitadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSerialDigitadoMouseClicked
        jButtonExcluirSerialSelecionado.setEnabled(true);
    }//GEN-LAST:event_jTableSerialDigitadoMouseClicked

    private void jButtonCancelarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarEntradaActionPerformed
        int cancelar = JOptionPane.showConfirmDialog(null, "CUIDADO!! \n SERÁ EXCLUIDO TODOS OS SERIAIS", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
        if (cancelar == JOptionPane.YES_NO_OPTION) {
            excluirSeriaisDoBanco();
            dispose();
            setVisible(false);
        }
    }//GEN-LAST:event_jButtonCancelarEntradaActionPerformed

    private void jButtonImprimirEtiquetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirEtiquetaActionPerformed
        List<SerialProduto> listText = new ArrayList<>();
        for (EntradaSerial s : queryIntegrador.listPorEntradaProd(movEntradaProd.getCodmoveprod())) {
            s.getIdSerial().setNomeProduto(movEntradaProd.getCodprod().getCodigo() + "-" + s.getIdSerial().getNomeProduto());
            listText.add(s.getIdSerial());
        }    
        new ImprimeRelatorio().imprimeRelatorioPeloJar(ConfiguracaoNoBD.getCaminhoEtiquetaSerial(), listText);
        dispose();
        setVisible(false);
    }//GEN-LAST:event_jButtonImprimirEtiquetaActionPerformed

    private void jToggleButtonEntradaSequencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEntradaSequencialActionPerformed
        if (!"".equals(jTextFieldPrimeiroSerial.getText()) && !"".equals(jTextFieldNumeroDeItens.getText())) {
            gerarSeriais(jTextFieldPrimeiroSerial.getText(), jTextFieldNumeroDeItens.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Os campos devem estár preenchidos!", "Erro Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButtonEntradaSequencialActionPerformed

    private void excluirSerialSelecionado() {
       // DefaultTableModel tabelaEntradaSerial = (DefaultTableModel) jTableSerialDigitado.getModel();
        int row = jTableSerialDigitado.getSelectedRow();
        int coluna = jTableSerialDigitado.getColumnModel().getColumnIndex("Serial");
        //tabelaEntradaSerial.removeRow(row);
        for (SerialProduto sp : queryIntegrador.listSerialExato((String) jTableSerialDigitado.getValueAt(row, coluna))) {
            if (sp.getSaidaSerialCollection().size() > 0) {
                JOptionPane.showMessageDialog(null, "\n O serial já possui uma saida.\n A mesma deve ser excluida antes de prosseguir! ");
            } else {
                for (EntradaSerial es : sp.getEntradaSerialCollection()) {
                    try {
                        new EntradaSerialJpaController(Manager.getManagerIntegrador()).destroy(es.getIdEntradaSerial());
                    } catch (NonexistentEntityException ex) {
                        tocarSomErro();
                        JOptionPane.showMessageDialog(null, "\n Erro ao Excluir Entrada Serial.\n " + ex);
                    }
                }
                try {
                    new SerialProdutoJpaController(Manager.getManagerIntegrador()).destroy(sp.getIdSerial());
                } catch (NonexistentEntityException ex) {
                    tocarSomErro();
                    JOptionPane.showMessageDialog(null, "\n Erro ao Excluir Serial Produto.\n " + ex);
                }
            }
        }
        jButtonExcluirSerialSelecionado.setEnabled(false);
        List<String> listTex = new ArrayList<>();
        for (EntradaSerial enSer : queryIntegrador.listPorEntradaProd(movEntradaProd.getCodmoveprod())) {
                listTex.add(String.valueOf(enSer.getIdSerial().getSerial()));
                //gravarProdutoSerial(String.valueOf(enSer));
            }
        criarTabela(listTex);
        confereQuantidadeDigitada();
    }

    private void criarTabela(List<String> listTex) {
        DefaultTableModel tabelaEntradaSerial = (DefaultTableModel) jTableSerialDigitado.getModel();
        int cont = jTableSerialDigitado.getRowCount();
        for (int a = 0; a < cont; a++) {
            tabelaEntradaSerial.removeRow(0);
        }
        for (String s : listTex) {
            tabelaEntradaSerial.addRow(new Object[]{String.valueOf(s)});
        }
        if (jTableSerialDigitado.getRowCount() != 0) {
            jTableSerialDigitado.setRowSelectionInterval(jTableSerialDigitado.getRowCount() - 1, jTableSerialDigitado.getRowCount() - 1);//seleciona ultima linha   
        }
    }

    private void gerarSeriais() {
        if (queryIntegrador.listPorEntradaProd(movEntradaProd.getCodmoveprod()).isEmpty()) {           
            Integer incrementSerial = Integer.valueOf(queryIntegrador.valorConfiguracao("increment_serial_gerado"));            
            int quantidadeEntrada = quantidadePacote;
            List<String> listTex = new ArrayList<>();          
            int count = 0;
            while (count < quantidadeEntrada) {
                jTableSerialDigitado.clearSelection(); //Tira linha selecionada 
                List<SerialProduto> produtoSerial = queryIntegrador.listSerialExato(String.valueOf(incrementSerial));
                if (produtoSerial.isEmpty()) {//if que verifica se o serial já existe no banco
                    listTex.add(String.valueOf(incrementSerial));
                    gravarProdutoSerial(String.valueOf(incrementSerial));
                    count++;
                }
                incrementSerial++;
            }
            try {
                queryIntegrador.atualizaValorConfiguracao("increment_serial_gerado", String.valueOf(incrementSerial));
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Houve um erro ao Gravar incrementSerial na Tabela Configuracao no Integrador!!!\n " + ex);
            }
            criarTabela(listTex);
            confereQuantidadeDigitada();
            tocarSomFinalizado();
        } else {
            tocarSomErro();
            JOptionPane.showMessageDialog(null, "JÁ EXISTEM ALGUNS SERIAIS GRAVADOS IMPOSSIVEL EXECUTAR A TAREFA!!");
        }
    }

    private void gerarSeriais(String primeiroSerial, String quantidadeSerial) {
        int quantidadeEntrada = quantidadePacote;
        if (Integer.valueOf(quantidadeSerial) <= quantidadeEntrada) {
            List<String> listTex = new ArrayList<>();
            long serialSequencia = Long.parseLong(primeiroSerial);
            int count = 0;
            for (EntradaSerial enSer : queryIntegrador.listPorEntradaProd(movEntradaProd.getCodmoveprod())) {
                listTex.add(String.valueOf(enSer.getIdSerial().getSerial()));
                //gravarProdutoSerial(String.valueOf(enSer));
            }
            while (Integer.valueOf(quantidadeSerial) > count) {
                jTextFieldSerial.setText(String.valueOf(serialSequencia));
                jTableSerialDigitado.clearSelection(); //Tira linha selecionada      
               // listTex.add(String.valueOf(serialSequencia));
                //gravarProdutoSerial(String.valueOf(serialSequencia));
                String format = String.format("%0"+primeiroSerial.length()+"d", serialSequencia);
                listTex.add(format);
                gravarProdutoSerial(format);
                
                serialSequencia++;
                count++;
            }
            jTextFieldPrimeiroSerial.setText("");
            criarTabela(listTex);
            confereQuantidadeDigitada();
            jTextFieldPrimeiroSerial.requestFocus();
            tocarSomFinalizado();

        } else {
            tocarSomErro();
            JOptionPane.showMessageDialog(null, "O numero de itens acima da quantidade de entrada!!");
        }
    }

    public void confereQuantidadeDigitada() {
        if (jTableSerialDigitado.getRowCount() == quantidadePacote) {
            jButtonGravar.setEnabled(true);
            jTextFieldSerial.setEnabled(false);
            jTextFieldSerial.setText("");
            jButtonGerarSeriais.setEnabled(false);
            jTextFieldQuantidadeFaltando.setText("0");
        } else {
            int quantFaltando = quantidadePacote - jTableSerialDigitado.getRowCount();
            jTextFieldQuantidadeFaltando.setText(String.valueOf(quantFaltando));
            if (jTableSerialDigitado.getRowCount() < 1) {
                jButtonGerarSeriais.setEnabled(true);
                jButtonExcluirSerialSelecionado.setEnabled(false);
            } else {
                jButtonGerarSeriais.setEnabled(false);
            }
            jButtonGravar.setEnabled(false);
            jTextFieldSerial.setEnabled(true);
            jTextFieldSerial.selectAll();
            jTextFieldSerial.requestFocus();
        }
    }

    private boolean gravarProdutoSerial(String serial) {
        boolean condicao = false;
        SerialProduto serialProd = new SerialProduto();//instancia classe
        serialProd.setCodProduto(produto.getCodprod());
        serialProd.setSerial(serial);//pega valor de jTable Serial
        serialProd.setCodigoProduto(produto.getCodigo());
        serialProd.setNomeProduto(produto.getNomeprod());
        serialProd.setData(new Date(System.currentTimeMillis()));
        try {
            new SerialProdutoJpaController(Manager.getManagerIntegrador()).create(serialProd);//Cria objeto no banco de dados
            if (gravarEntradaSerial(new SerialProdutoJpaController(Manager.getManagerIntegrador()).findSerialProduto(serialProd.getIdSerial()))) {
                // condicao = true;
            }
        } catch (Exception ex) {
            tocarSomErro();
            JOptionPane.showMessageDialog(null, "\n Erro ao gravar produto Serial.\n " + ex);
            // condicao = true;
        }
        return condicao;
    }

    private boolean gravarEntradaSerial(SerialProduto produtoSerial) {
        boolean condicao = false;
        EntradaSerial ent = new EntradaSerial();
        ent.setIdSerial(produtoSerial);
        ent.setCodEntradaProd(movEntradaProd.getCodmoveprod());
        ent.setCodEntrada(movEntradaProd.getCodmoventr().getCodmoventr());
        ent.setDevolvido(false);
        ent.setDataEntrada(new Date(System.currentTimeMillis()));
        try {
            new EntradaSerialJpaController(Manager.getManagerIntegrador()).create(ent);
        } catch (Exception ex) {
            tocarSomErro();
            JOptionPane.showMessageDialog(null, "\n Erro ao gravar Entrada Serial.\n " + ex);
            condicao = true;
        }
        return condicao;
    }

    private void excluirSeriaisDoBanco() {
        List<EntradaSerial> listMovProdSerial = queryIntegrador.listPorEntradaProd(movEntradaProd.getCodmoveprod());
        for (EntradaSerial ent : listMovProdSerial) {
            try {
                new EntradaSerialJpaController(Manager.getManagerIntegrador()).destroy(ent.getIdEntradaSerial());
                new SerialProdutoJpaController(Manager.getManagerIntegrador()).destroy(ent.getIdSerial().getIdSerial());
            } catch (NonexistentEntityException ex) {
                tocarSomErro();
                JOptionPane.showMessageDialog(null, "\n Erro ao Excluir Entrada Serial.\n " + ex);
            }
        }
        jButtonGravar.setEnabled(true);
    }

    private void verificaSerial() {
        String textoDigitado = jTextFieldSerial.getText().toUpperCase().trim();
        List<SerialProduto> produtoSerial = queryIntegrador.listSerialExato(textoDigitado);
        if (produtoSerial.isEmpty()) {//if que verifica se o serial já existe no banco
            if (serialCadastroEntrada(textoDigitado)) {//if que verifica se o serial já está na tabela
                if (verificaQuantidade()) {//if que verifica se a quantidade digitada foi exedida
                    if (verificaCodigos(textoDigitado)) {
                        DefaultTableModel tabelaEntradaSerial = (DefaultTableModel) jTableSerialDigitado.getModel();
                        jTableSerialDigitado.clearSelection(); //Tira linha selecionada
                        tabelaEntradaSerial.addRow(new Object[]{textoDigitado});
                        gravarProdutoSerial(textoDigitado);
                        jTableSerialDigitado.setRowSelectionInterval(jTableSerialDigitado.getRowCount() - 1, jTableSerialDigitado.getRowCount() - 1);//seleciona ultima linha                        
                    } else {
                        tocarSomErro();
                        JOptionPane.showMessageDialog(null, "Não pode ser EAN ou outros Códigos!!!");
                        this.listagemUsuarioJDialog.setVisible(true);
                    }
                } else {
                    tocarSomErro();
                    JOptionPane.showMessageDialog(null, "A Entrada de Serial desse Produto já está completa!!!!!");
                    this.listagemUsuarioJDialog.setVisible(true);
                }
            } else {
                tocarSomErro();
                JOptionPane.showMessageDialog(null, "O Serial já está na tabela!!! \n Serial: " + textoDigitado);
                this.listagemUsuarioJDialog.setVisible(true);
            }
        } else {//else que verifica se ha serial cadastrado
            tocarSomErro();
            JOptionPane.showMessageDialog(null, "O Serial digitado já está cadastrado!!! \n" + produtoSerial.size() + " Resultados encontrados");
            this.listagemUsuarioJDialog.setVisible(true);
        }
        confereQuantidadeDigitada();
    }

    private boolean verificaCodigos(String textoDigitado) {
        boolean condicao = true;
        if (produto.getCodigo() == null ? textoDigitado == null : produto.getCodigo().equals(textoDigitado)) {
            condicao = false;
        } else {
            for (Produtocodigo cod : listCodigo) {
                if (cod.getCodigo() == null ? textoDigitado == null : cod.getCodigo().equals(textoDigitado)) {
                    condicao = false;
                }
            }
        }
        return condicao;
    }

    private boolean verificaQuantidade() {
        boolean condicao = true;
        // int cont = jTableSerialDigitado.getRowCount();
        if (jTableSerialDigitado.getRowCount() > quantidadePacote) {
            condicao = false;
        }
        return condicao;
    }

    private boolean serialCadastroEntrada(String textoDigitado) {
        boolean condicao = true;
        int totalLinhaSerial = jTableSerialDigitado.getRowCount();
        String serialTabela;
        colunaSerial = jTableSerialDigitado.getColumnModel().getColumnIndex("Serial");
        for (int linhaSerial = 0; linhaSerial < totalLinhaSerial; linhaSerial++) {
            serialTabela = jTableSerialDigitado.getValueAt(linhaSerial, colunaSerial).toString();
            if (serialTabela.equals(textoDigitado)) {
                jTableSerialDigitado.setRowSelectionInterval(linhaSerial, linhaSerial);
                condicao = false;
                break;
            }
        }
        return condicao;
    }

    private int quantidadePacote(Moventradaprod prodEnt) {
        int quantidade = prodEnt.getQuantidade().intValue();
        List<Unidade> listUn = queryCplus.resultPorUnidadeProduto(prodEnt.getCodprod().getUnidade());
        for (Unidade un : listUn) {
            if (un.getFatorconversao().intValue() > 1) {
                quantidade = quantidade / un.getFatorconversao().intValue();
            }
        }
        //quantidade = quantidade - queryCplus.listagemSerialEntradaProd(prodEnt.getCodmoveprod()).size();
        return quantidade;
    }

    private void tocarSomErro() {
        String path = queryIntegrador.valorConfiguracao("caminho_ARQUIVO_AUDIO_ERRO");
        File mp3File = new File(path);
        ReproduzirAudio musica = new ReproduzirAudio(mp3File);
        musica.play();
    }

    private void tocarSomFinalizado() {
        String path = queryIntegrador.valorConfiguracao("caminho_ARQUIVO_AUDIO_FINALIZADO");
        File mp3File = new File(path);
        ReproduzirAudio musica = new ReproduzirAudio(mp3File);
        musica.play();
    }

    public void setMovEntradaProd(Moventradaprod movEntradaProd) {
        this.quantidadePacote = quantidadePacote(movEntradaProd);
        this.movEntradaProd = movEntradaProd;
        List<String> listTex = new ArrayList<>();
        for (EntradaSerial s : queryIntegrador.listPorEntradaProd(movEntradaProd.getCodmoveprod())) {
            listTex.add(s.getIdSerial().getSerial());
        }
        criarTabela(listTex);
    }

    public void setListCodigo(List<Produtocodigo> listCodigo) {
        this.listCodigo = listCodigo;
    }

    public void setProduto(Produto produto) {
        this.produto = produto;
        jTextFieldEstoqueCplus.setText(EstoqueCplus(produto.getCodprod()));
        jTextFieldSetor.setText(setor(produto));
    }
    
     private String setor(Produto codProd){
        String text = "";
        for(Localizacao loc : queryCplus.listLocalizacao(codProd.getCodloc())){
            text =  loc.getDescricao();
        }             
        return text;
    }
    
     private String EstoqueCplus(String codProd) {
        BigDecimal estoque = BigDecimal.ZERO;
        List<Produtoestoque> listEsroque = new QueryCplus().listEstoquesPorProd(codProd);
        for (Produtoestoque est : listEsroque) {
            estoque = est.getEstatu().subtract(est.getReservadoorcamento().subtract(est.getReservadoos()));
        }
        return String.valueOf(estoque.intValue());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaSerialJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EntradaSerialJDialog dialog = new EntradaSerialJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private final QueryCplus queryCplus;
    private final QueryIntegrador queryIntegrador;
    //private static EntityManagerFactory managerCplus;
    //private static EntityManagerFactory managerIntegrador;
    private Moventradaprod movEntradaProd;
    private final ListagemUsuarioJDialog listagemUsuarioJDialog;
    private int colunaSerial;
    private List<Produtocodigo> listCodigo;
    private Produto produto;
    private int quantidadePacote;
    //private final ListagemLocalizacaoJDialog listagemLocalizacaoJDialog;
    private final ListagemProdutoJDialog listagemProdutoJDialog;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarEntrada;
    private javax.swing.JButton jButtonExcluirSerialSelecionado;
    private javax.swing.JButton jButtonGerarSeriais;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonImprimirEtiqueta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDigiteSerial;
    private javax.swing.JLabel jLabelEstoqueTotal;
    private javax.swing.JLabel jLabelQuantidadeFaltando;
    private javax.swing.JLabel jLabelSetor;
    private javax.swing.JPanel jPanelControle;
    private javax.swing.JPanel jPanelInformacoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSerialDigitado;
    private javax.swing.JTextField jTextFieldEstoqueCplus;
    private javax.swing.JTextField jTextFieldNumeroDeItens;
    private javax.swing.JTextField jTextFieldPrimeiroSerial;
    private javax.swing.JTextField jTextFieldQuantidadeFaltando;
    private javax.swing.JTextField jTextFieldSerial;
    private javax.swing.JTextField jTextFieldSetor;
    private javax.swing.JToggleButton jToggleButtonEntradaSequencial;
    // End of variables declaration//GEN-END:variables
}
