/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package integrador.separacao;

import acesso.ListagemUsuarioJDialog;
import entidade.cplus.Localizacao;
import entidade.cplus.Movenda;
import entidade.cplus.Movendaprod;
import entidade.cplus.Movendaprodserial;
import entidade.cplus.Produto;
import entidade.cplus.Produtocodigo;
import entidade.cplus.Produtoestoque;
import entidade.cplus.Produtoserial;
import entidade.cplus.Unidade;
import entidade.integrador.IntConfiguracao;
import entidade.integrador.IntLogs;
import entidade.integrador.SaidaSerial;
import entidade.integrador.SerialProduto;
import integrador.relatorio.ImprimeRelatorio;
import integrador.render.ConfTabelaSaidaSerial;
import integrador.render.ConfTabelaSaidaSerialProd;
import janela.cplus.FormataCampos;
import janela.cplus.ListagemProdutoJDialog;
import janela.cplus.ListagemSaidasJDialog;
import java.awt.Toolkit;
import java.io.File;
import java.math.BigDecimal;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jpa.cplus.MovendaJpaController;
import jpa.cplus.MovendaprodJpaController;
import jpa.cplus.ProdutoJpaController;
import jpa.cplus.exceptions.NonexistentEntityException;
import jpa.integrador.IntConfiguracaoJpaController;
import jpa.integrador.IntLogsJpaController;
import jpa.integrador.SaidaSerialJpaController;
import prestashop.ConfiguracaoNoBD;
import prestashop.Manager;
import query.cplus.QueryCplus;
import query.integrador.QueryIntegrador;

/**
 *
 * @author leonardo
 */
public class SaidaSerialJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SaidaSerialJFrame
     */
    public SaidaSerialJFrame() {
        initComponents();
        queryCplus = new QueryCplus();
        queryIntegrador = new QueryIntegrador();
        this.listagemSaidasJDialog = new ListagemSaidasJDialog(this, true);
        this.listagemUsuarioJDialog = new ListagemUsuarioJDialog(this, true);
        this.listagemUsuarioJDialog.setLocationRelativeTo(null);
        this.listagemUsuarioJDialog.requestFocusInWindow();
        this.listagemSaidasJDialog.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icones/logo.png")));
        this.listagemProdutoJDialog = new ListagemProdutoJDialog(this, true);
        // new RenderLocalizacao(Manager.getManagerCplus());
        jTableSaidaProd.setDefaultRenderer(Object.class, new ConfTabelaSaidaSerialProd());
        jTableSeriasSeparados.setDefaultRenderer(Object.class, new ConfTabelaSaidaSerial());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConfiguracaoLista = new javax.swing.JPanel();
        jButtonImprimirRomaneio = new javax.swing.JButton();
        jButtonExcluirSeria = new javax.swing.JButton();
        jButtonEditarProduto = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jTextFieldTextoAviso = new javax.swing.JTextField();
        jPanelInformacoes = new javax.swing.JPanel();
        jLabelItensFaltando = new javax.swing.JLabel();
        jTextFieldItensFaltando = new javax.swing.JTextField();
        jTextFieldMultiplo = new javax.swing.JTextField();
        jTextFieldSerial = new javax.swing.JTextField();
        jLabelDigiteSerial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelPesquisas = new javax.swing.JPanel();
        jButtonPesquisaSaida = new javax.swing.JButton();
        jButtonSepararPedido = new javax.swing.JButton();
        jButtonCancelarSeparacao = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSaidaProd = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSeriasSeparados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Separação Serial");

        jPanelConfiguracaoLista.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurações Listagem Serial"));

        jButtonImprimirRomaneio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonImprimirRomaneio.setText("Imprimir Romaneio");
        jButtonImprimirRomaneio.setEnabled(false);
        jButtonImprimirRomaneio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirRomaneioActionPerformed(evt);
            }
        });

        jButtonExcluirSeria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonExcluirSeria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        jButtonExcluirSeria.setText("Excluir Serial");
        jButtonExcluirSeria.setEnabled(false);
        jButtonExcluirSeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirSeriaActionPerformed(evt);
            }
        });

        jButtonEditarProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Edit.png"))); // NOI18N
        jButtonEditarProduto.setText("Editar Produto");
        jButtonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProdutoActionPerformed(evt);
            }
        });

        jButtonFechar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/stop.png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelConfiguracaoListaLayout = new javax.swing.GroupLayout(jPanelConfiguracaoLista);
        jPanelConfiguracaoLista.setLayout(jPanelConfiguracaoListaLayout);
        jPanelConfiguracaoListaLayout.setHorizontalGroup(
            jPanelConfiguracaoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfiguracaoListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConfiguracaoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonImprimirRomaneio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExcluirSeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );
        jPanelConfiguracaoListaLayout.setVerticalGroup(
            jPanelConfiguracaoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfiguracaoListaLayout.createSequentialGroup()
                .addGroup(jPanelConfiguracaoListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImprimirRomaneio)
                    .addComponent(jButtonFechar))
                .addGap(42, 42, 42)
                .addComponent(jButtonExcluirSeria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextFieldTextoAviso.setEditable(false);
        jTextFieldTextoAviso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jPanelInformacoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Serial:"));

        jLabelItensFaltando.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelItensFaltando.setText("Itens Faltando:");

        jTextFieldItensFaltando.setEditable(false);
        jTextFieldItensFaltando.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jTextFieldMultiplo.setEditable(false);
        jTextFieldMultiplo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldMultiplo.setText("1");

        jTextFieldSerial.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jTextFieldSerial.setEnabled(false);
        jTextFieldSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerialActionPerformed(evt);
            }
        });

        jLabelDigiteSerial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDigiteSerial.setText("Digite o Serial:");

        jLabel1.setText("Multiplo:");

        javax.swing.GroupLayout jPanelInformacoesLayout = new javax.swing.GroupLayout(jPanelInformacoes);
        jPanelInformacoes.setLayout(jPanelInformacoesLayout);
        jPanelInformacoesLayout.setHorizontalGroup(
            jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInformacoesLayout.createSequentialGroup()
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelDigiteSerial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelItensFaltando, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                        .addComponent(jTextFieldItensFaltando, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMultiplo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldSerial)))
        );
        jPanelInformacoesLayout.setVerticalGroup(
            jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacoesLayout.createSequentialGroup()
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldItensFaltando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelItensFaltando))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMultiplo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDigiteSerial)))
        );

        jPanelPesquisas.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa:"));

        jButtonPesquisaSaida.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonPesquisaSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jButtonPesquisaSaida.setText("Pesquisa Saida");
        jButtonPesquisaSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaSaidaActionPerformed(evt);
            }
        });

        jButtonSepararPedido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonSepararPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/play.png"))); // NOI18N
        jButtonSepararPedido.setText("Separar Pedido");
        jButtonSepararPedido.setEnabled(false);
        jButtonSepararPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSepararPedidoActionPerformed(evt);
            }
        });

        jButtonCancelarSeparacao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonCancelarSeparacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        jButtonCancelarSeparacao.setText("Cancelar Separação");
        jButtonCancelarSeparacao.setEnabled(false);
        jButtonCancelarSeparacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarSeparacaoActionPerformed(evt);
            }
        });

        jButtonGravar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonGravar.setText("Gravar");
        jButtonGravar.setEnabled(false);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPesquisasLayout = new javax.swing.GroupLayout(jPanelPesquisas);
        jPanelPesquisas.setLayout(jPanelPesquisasLayout);
        jPanelPesquisasLayout.setHorizontalGroup(
            jPanelPesquisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisasLayout.createSequentialGroup()
                .addGroup(jPanelPesquisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPesquisaSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButtonGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanelPesquisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelarSeparacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSepararPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPesquisasLayout.setVerticalGroup(
            jPanelPesquisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisasLayout.createSequentialGroup()
                .addGroup(jPanelPesquisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPesquisaSaida)
                    .addComponent(jButtonSepararPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesquisasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelarSeparacao)
                    .addComponent(jButtonGravar)))
        );

        jTableSaidaProd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTableSaidaProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Produto", "Quantidade", "Separado", "Setor", "Estoque", "Unidade", "Cod. MovProd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSaidaProd.setColumnSelectionAllowed(true);
        jTableSaidaProd.setRequestFocusEnabled(false);
        jTableSaidaProd.setRowHeight(25);
        jTableSaidaProd.getTableHeader().setReorderingAllowed(false);
        jTableSaidaProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSaidaProdMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableSaidaProd);
        jTableSaidaProd.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableSaidaProd.getColumnModel().getColumnCount() > 0) {
            jTableSaidaProd.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableSaidaProd.getColumnModel().getColumn(1).setPreferredWidth(400);
            jTableSaidaProd.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTableSaidaProd.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTableSaidaProd.getColumnModel().getColumn(4).setPreferredWidth(30);
            jTableSaidaProd.getColumnModel().getColumn(5).setPreferredWidth(30);
            jTableSaidaProd.getColumnModel().getColumn(7).setPreferredWidth(5);
        }

        jTableSeriasSeparados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableSeriasSeparados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Serial", "ID Saida Serial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSeriasSeparados.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableSeriasSeparados.setColumnSelectionAllowed(true);
        jTableSeriasSeparados.getTableHeader().setReorderingAllowed(false);
        jTableSeriasSeparados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSeriasSeparadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSeriasSeparados);
        jTableSeriasSeparados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableSeriasSeparados.getColumnModel().getColumnCount() > 0) {
            jTableSeriasSeparados.getColumnModel().getColumn(0).setPreferredWidth(120);
            jTableSeriasSeparados.getColumnModel().getColumn(1).setPreferredWidth(350);
            jTableSeriasSeparados.getColumnModel().getColumn(2).setPreferredWidth(140);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelPesquisas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelConfiguracaoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldTextoAviso, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanelPesquisas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelConfiguracaoLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTextoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaSaidaActionPerformed
        buscaPedido();
    }//GEN-LAST:event_jButtonPesquisaSaidaActionPerformed

    private void jButtonSepararPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSepararPedidoActionPerformed
        jTextFieldSerial.setEnabled(true);
        jTextFieldSerial.requestFocus();
        jButtonPesquisaSaida.setEnabled(false);
        jButtonFechar.setEnabled(false);
        jButtonCancelarSeparacao.setEnabled(true);
        pedidoSeparado(false);
        jButtonSepararPedido.setEnabled(false);
        //tratamentoCampos();
    }//GEN-LAST:event_jButtonSepararPedidoActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        fechar();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonExcluirSeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirSeriaActionPerformed
        removerSerialSelecionado();
    }//GEN-LAST:event_jButtonExcluirSeriaActionPerformed

    private void jButtonCancelarSeparacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarSeparacaoActionPerformed
        int cancelar = JOptionPane.showConfirmDialog(null, "AO CANCELAR O PEDIDO OS SERIAIS DIGITADOS SERÃO PERDIDOS,\n DESEJA PROSSEGUIR??", "Cancelar", JOptionPane.YES_NO_CANCEL_OPTION);
        if (cancelar == JOptionPane.YES_OPTION) {
            jButtonFechar.setEnabled(true);
            jButtonPesquisaSaida.setEnabled(true);
            jButtonCancelarSeparacao.setEnabled(false);
            //jButtonGravar.setEnabled(false);
            buscaPedido();
        }
    }//GEN-LAST:event_jButtonCancelarSeparacaoActionPerformed

    private void jTextFieldSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerialActionPerformed

        adicionarSerial();
    }//GEN-LAST:event_jTextFieldSerialActionPerformed

    private void jButtonImprimirRomaneioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirRomaneioActionPerformed
        if (movenda != null) {
            List<Movendaprod> movendaprodList = new ArrayList<>();
            for (Movendaprod movProd : movenda.getMovendaprodCollection()) {
                movendaprodList.add(movProd);
                List<Movendaprodserial> listMovSerial = new ArrayList<>();
                for (SaidaSerial sai : queryIntegrador.listPorSaidaProd(movProd.getCodmovprod())) {
                    Produtoserial serp = new Produtoserial();
                    serp.setCodprodutoserial(sai.getIdSerial().getIdSerial().toString());
                    serp.setCodprod(movProd.getCodprod());
                    serp.setSerial(sai.getIdSerial().getSerial());
                    Movendaprodserial sp = new Movendaprodserial();
                    sp.setCodmovendaprodserial(sai.getIdSaidaSerial().toString());
                    sp.setCodmovprod(movProd);
                    sp.setCodprodutoserial(serp);
                    listMovSerial.add(sp);
                }
                movProd.setMovendaprodserialCollection(listMovSerial);
            }
            new ImprimeRelatorio().imprimeRelatorioPeloJar(ConfiguracaoNoBD.getValorRomaneioSeriais(), movendaprodList);
        }
    }//GEN-LAST:event_jButtonImprimirRomaneioActionPerformed

    private void jTableSeriasSeparadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSeriasSeparadosMouseClicked
        jButtonExcluirSeria.setEnabled(true);
        jButtonImprimirRomaneio.setEnabled(true);
    }//GEN-LAST:event_jTableSeriasSeparadosMouseClicked

    private void jTableSaidaProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSaidaProdMouseClicked
        //jButtonEditarProduto.setEnabled(true);
    }//GEN-LAST:event_jTableSaidaProdMouseClicked

    private void jButtonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProdutoActionPerformed

        if (jTableSaidaProd.getRowCount() > 0 && jTableSaidaProd.getSelectedRow() != -1) {
            int colunaCodMovProd = jTableSaidaProd.getColumnModel().getColumnIndex("Cod. MovProd");
            String codMovProd = jTableSaidaProd.getValueAt(jTableSaidaProd.getSelectedRow(), colunaCodMovProd).toString();
            Movendaprod movEntradaProd = new MovendaprodJpaController(Manager.getManagerCplus()).findMovendaprod(codMovProd);
            this.listagemProdutoJDialog.setTermoPesquisa(movEntradaProd.getCodprod().getCodigo());
            this.listagemProdutoJDialog.setVisible(true);
            // jButtonEditarProduto.setEnabled(false);
        } else {
            this.listagemProdutoJDialog.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditarProdutoActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        gravarSaidaSerial();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    /**
     * Função que carrega uma lista de EAN dos Produtos que estão no pedido A
     * função tambem carega a List <ListCodigoProduto> listCodigo
     */
    private void carregaListaCodigos() {
        listCodigo = new ArrayList<>();
        for (Movendaprod p : listMovendaProd) {
            for (Produtocodigo cod : queryCplus.listEanProduto(p.getCodprod().getCodprod())) {
                ListCodigoProduto e = new ListCodigoProduto();
                e.setId_Codigo(cod.getId());
                e.setCodigo(cod.getCodigo());
                e.setCod_prod(cod.getCodprod().getCodprod());
                listCodigo.add(e);
            }
        }
    }

    /**
     * Função que percore a lista de seriais da saida e verifica se a quantidade
     * de seriais do item da venda que estão na lista de Saida retorna o numnero
     * de Seriais do Item do pedido
     *
     * @param movProd
     * @param listSS
     * @return
     */
    private int produtoSeparado(Movendaprod movProd, List<SaidaSerial> listSS) {
        //boolean condicao = true;
        int cont = 0;
        for (SaidaSerial ss : listSS) {
            if (ss.getCodSaidaProd().equals(movProd.getCodmovprod())) {
                cont++;
            }
        }
        return cont;
    }

    /**
     * Função que percore a lista de seriais para ver se o mesmo já se encontra
     * na lista
     *
     * @param serial
     * @param listSS
     * @return
     */
    private boolean produtoDuplicado(String serial, List<SaidaSerial> listSS) {
        boolean condicao = true;
        //int cont = 0;
        for (SaidaSerial ss : listSS) {
            if (ss.getIdSerial().getSerial().equals(serial)) {
                condicao = false;
            }
        }
        return condicao;
    }

    /**
     * Função responsável por verificar se ha erro coo o serial digitado
     */
    private void adicionarSerial() {
        int quantSeparada = 0;
        boolean condicao = false;
        if (!"".equals(jTextFieldSerial.getText())) {
            List<SerialProduto> listSer = queryIntegrador.listSerialExato(jTextFieldSerial.getText().toUpperCase().trim());
            if (listSer.size() == 1) {
                if (verificaCodigos(jTextFieldSerial.getText().toUpperCase().trim())) {
                    for (SerialProduto ser : listSer) {
                        int quantProdTotal = 0;
                        int serialProdutoSeparado = 0;
                        int quantTotalPedido = 0;
                        for (Movendaprod movProd : listMovendaProd) {
                            if (ser.getCodProduto().equals(movProd.getCodprod().getCodprod())) {
                                condicao = true;
                            }
                        }
                        if (condicao) {
                            for (SaidaSerial ss : listSaidaSerial) {
                                if (ss.getIdSerial().getSerial().equals(jTextFieldSerial.getText().toUpperCase().trim())) {
                                    condicao = false;
                                    manutencaoDeErro("O Serial: " + ss.getIdSerial().getSerial() + ", já está no pedido!!");
                                }
                            }
                        } else {
                            manutencaoDeErro("O Produto: " + ser.getNomeProduto() + ", não está no pedido!!");
                            condicao = false;
                        }

                        if (condicao) {
                            for (Movendaprod movProd : listMovendaProd) {
                                quantTotalPedido = quantTotalPedido + movProd.getQuantidade().intValue();
                                if (movProd.getCodprod().getCodprod().equals(ser.getCodProduto())) {
                                    quantProdTotal = quantProdTotal + movProd.getQuantidade().intValue();
                                    serialProdutoSeparado = serialProdutoSeparado + produtoSeparado(movProd, listSaidaSerial);
                                }
                            }
                        }

                        if (condicao) {
                            boolean jaPassou = true;
                            for (Movendaprod movProd : listMovendaProd) {
                                if (movProd.getCodprod().getCodprod().equals(ser.getCodProduto())) {
                                    int quan = produtoSeparado(movProd, listSaidaSerial);
                                    if (movProd.getQuantidade().intValue() > quan && produtoDuplicado(ser.getSerial(), listSaidaSerial)) {
                                        quantSeparada = quan + 1;
                                        SaidaSerial a = new SaidaSerial();
                                        a.setIdSaidaSerial(0);
                                        a.setCodSaidaProd(movProd.getCodmovprod());
                                        a.setDataSaida(format.dataAtual());
                                        a.setCodSaida(movProd.getCodmovenda().getCodmovenda());
                                        a.setIdSerial(ser);
                                        listSaidaSerial.add(a);
                                        carregaTabelasAdicionar(movProd, quantSeparada);
                                        pedidoSeparado(true);
                                        if (quantTotalPedido == listSaidaSerial.size()) {
                                            jButtonGravar.setEnabled(true);
                                        }
                                    } else {
                                        if (quantProdTotal == serialProdutoSeparado) {
                                            manutencaoDeErro("O produto: " + ser.getNomeProduto() + ", está totalmente separado!!");
                                        }
                                    }
                                }
                            }
                        }
                    }
                } else {
                    manutencaoDeErro("O serial não pode ser o EAN, Verifique!!");
                }
            } else {
                manutencaoDeErro("Serial não encontrado: " + jTextFieldSerial.getText() + " Verifique!!");
            }
        } else {
            manutencaoDeErro("Você deve digitar algo Verifique!!");
        }
        //carregaTabelas();
        jTextFieldSerial.selectAll();
        jTextFieldSerial.setText("");
        jTextFieldSerial.requestFocus();
    }

    /**
     * Função responsável por carregar tabelas na hora da separação
     * @param movProd
     * @param quantSeparada 
     */
    private void carregaTabelasAdicionar(Movendaprod movProd, int quantSeparada) {
        DefaultTableModel tabSaidaProd = (DefaultTableModel) jTableSaidaProd.getModel();
        while (jTableSaidaProd.getModel().getRowCount() > 0) {
            ((DefaultTableModel) jTableSaidaProd.getModel()).removeRow(0);
        }
        int linha = 0;
        for (Movendaprod e : listMovendaProd) {
            int coluna = jTableSaidaProd.getColumnModel().getColumnIndex("Cod. MovProd");
            int colunaSeparado = jTableSaidaProd.getColumnModel().getColumnIndex("Separado");
            tabSaidaProd.addRow(new Object[]{
                e.getCodprod().getCodigo(),
                e.getCodprod().getNomeprod(),
                //String.valueOf(quantidadePacote(e)),
                String.valueOf(e.getQuantidade().intValue()),
                //String.valueOf(queryIntegrador.listPorSaidaProd(e.getCodmovprod()).size()),
                String.valueOf(produtoSeparado(e, listSaidaSerial)),
                e.getCodigoeanproduto(), //se refere a localização ou setor
                String.valueOf(e.getComissao().intValue()), //se refere ao estoque
                e.getUnidade(),
                e.getCodmovprod()
            });

            String value = (String) jTableSaidaProd.getValueAt(linha, coluna);
            if (movProd.getCodmovprod() == null ? value == null : movProd.getCodmovprod().equals(value)) {
                tabSaidaProd.setValueAt(quantSeparada, linha, colunaSeparado);
            }
            linha++;
        }
        DefaultTableModel tabSerial = (DefaultTableModel) jTableSeriasSeparados.getModel();
        while (jTableSeriasSeparados.getModel().getRowCount() > 0) {
            ((DefaultTableModel) jTableSeriasSeparados.getModel()).removeRow(0);
        }
        for (SaidaSerial s : listSaidaSerial) {
            tabSerial.addRow(new Object[]{
                s.getIdSerial().getCodigoProduto(),
                s.getIdSerial().getNomeProduto(),
                s.getIdSerial().getSerial(),
                String.valueOf(s.getIdSaidaSerial())
            });
        }
        int lastRow = jTableSeriasSeparados.getRowCount() - 1;
        if (lastRow >= 0) {
            jTableSeriasSeparados.scrollRectToVisible(jTableSeriasSeparados.getCellRect(lastRow, 0, true));
        }

    }

    /**
     * Retorna a localização
     * @param codProd
     * @return 
     */
    private String setor(Produto codProd) {
        String text = "";
        for (Localizacao loc : queryCplus.listLocalizacao(codProd.getCodloc())) {
            text = loc.getDescricao();
        }
        return text;
    }

    private Integer EstoqueCplus(String codProd) {
        BigDecimal estoque = BigDecimal.ZERO;
        List<Produtoestoque> listEsroque = new QueryCplus().listEstoquesPorProd(codProd);
        for (Produtoestoque est : listEsroque) {
            estoque = est.getEstatu().subtract(est.getReservadoorcamento().subtract(est.getReservadoos()));
        }
        return estoque.intValue();
    }

    private void carregaTabelas() {
        DefaultTableModel tab = (DefaultTableModel) jTableSaidaProd.getModel();
        while (jTableSaidaProd.getModel().getRowCount() > 0) {
            ((DefaultTableModel) jTableSaidaProd.getModel()).removeRow(0);
        }
        for (Movendaprod e : listMovendaProd) {
            tab.addRow(new Object[]{
                e.getCodprod().getCodigo(),
                e.getCodprod().getNomeprod(),
                //String.valueOf(quantidadePacote(e)),
                String.valueOf(e.getQuantidade().intValue()),
                String.valueOf(produtoSeparado(e, listSaidaSerial)),
                e.getCodigoeanproduto(), //se refere a localização ou setor
                String.valueOf(e.getComissao().intValue()), //se refere ao estoque
                e.getUnidade(),
                e.getCodmovprod()
            });
        }

        DefaultTableModel tabSerial = (DefaultTableModel) jTableSeriasSeparados.getModel();
        while (jTableSeriasSeparados.getModel().getRowCount() > 0) {
            ((DefaultTableModel) jTableSeriasSeparados.getModel()).removeRow(0);
        }
        for (SaidaSerial s : listSaidaSerial) {
            tabSerial.addRow(new Object[]{
                s.getIdSerial().getCodigoProduto(),
                s.getIdSerial().getNomeProduto(),
                s.getIdSerial().getSerial(),
                String.valueOf(s.getIdSaidaSerial())
            });
        }
        if (jTableSeriasSeparados.getRowCount() != 0) {
            jTableSeriasSeparados.setRowSelectionInterval(jTableSeriasSeparados.getRowCount() - 1, jTableSeriasSeparados.getRowCount() - 1);//seleciona ultima linha   
            jButtonImprimirRomaneio.setEnabled(true);
        } else {
            jButtonImprimirRomaneio.setEnabled(false);
        }
    }

    /**
     * Função que passa pela listagem de EANs do pedido Caso algum seja igual ao
     * serial digitado retorna false
     *
     * @param textoDigitado
     * @return
     */
    private boolean verificaCodigos(String textoDigitado) {
        boolean condicao = true;

        for (ListCodigoProduto p : listCodigo) {
            if (p.getCodigo().equals(textoDigitado)) {
                condicao = false;
            }
        }

        return condicao;
    }

    private void manutencaoDeErro(String mensagem) {
        tocarSomErro();
        JOptionPane.showMessageDialog(null, mensagem, "Erro Separar", JOptionPane.ERROR_MESSAGE);
        this.listagemUsuarioJDialog.setVisible(true);
        String getStr = "";
        if (movenda.getObs() != null) {
            getStr = movenda.getObs();
        }
        movenda.setObs(getStr + "Usuário: " + this.listagemUsuarioJDialog.getUsuario().getNome() + " " + mensagem + "\n");
        try {
            new MovendaJpaController(Manager.getManagerCplus()).edit(movenda);
        } catch (NonexistentEntityException ex) {
            criaLog(new Date(System.currentTimeMillis()), "Erro ao editar Pedido: " + ex, "Erro editar");
        } catch (Exception ex) {
            criaLog(new Date(System.currentTimeMillis()), "Erro ao editar Pedido: " + ex, "Erro editar");
        }
        criaLog(new Date(System.currentTimeMillis()), "Erro separarar, pedido: " + movenda.getNumped() + ", Usuário: " + this.listagemUsuarioJDialog.getUsuario().getNome() + mensagem + "\n", "Erro Separar");
    }

    private void removerSerialSelecionado() {
        // if (pedidoSeparado()) {
        //jButtonExcluirSeria.setEnabled(true);
        if (jTableSeriasSeparados.getSelectedRow() >= 0) {
            int coluna = jTableSeriasSeparados.getColumnModel().getColumnIndex("ID Saida Serial");
            Integer aValue = Integer.valueOf(jTableSeriasSeparados.getValueAt(jTableSeriasSeparados.getSelectedRow(), coluna).toString());
            if (aValue > 0) {
                try {
                    new SaidaSerialJpaController(Manager.getManagerIntegrador()).destroy(aValue);
                } catch (jpa.integrador.exceptions.NonexistentEntityException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir serial!! \n" + ex);
                }
            }
            coluna = jTableSeriasSeparados.getColumnModel().getColumnIndex("Serial");
            String txt = jTableSeriasSeparados.getValueAt(jTableSeriasSeparados.getSelectedRow(), coluna).toString();
            listSaidaSerial.removeIf(p -> p.getIdSerial().getSerial().equals(txt));
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        }
        //}
        jTextFieldSerial.selectAll();
        jTextFieldSerial.setText("");
        jTextFieldSerial.requestFocus();
        jButtonExcluirSeria.setEnabled(false);
        carregaTabelas();
        pedidoSeparado(false);
    }

    private void fechar() {
        boolean condicao = true;
        List<IntConfiguracao> listConfig = queryIntegrador.listagemConfiguracaoproTipoConfiguracao(retornaIpLocal());
        for (IntConfiguracao config : listConfig) {
            try {
                new IntConfiguracaoJpaController(Manager.getManagerIntegrador()).destroy(config.getEntityId());
            } catch (jpa.integrador.exceptions.NonexistentEntityException ex) {
                condicao = false;
                JOptionPane.showMessageDialog(null, "HOUVE UM ERRO AO EXCLUIR CONFIGURACAO, Verifique!! \n" + ex, "Erro Separar", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (condicao) {
            dispose();
            setVisible(false);
        }
    }

    private String retornaIpLocal() {
        InetAddress ia = null;
        try {
            ia = InetAddress.getLocalHost();
        } catch (UnknownHostException e) {
            JOptionPane.showMessageDialog(null, "HOUVE UM ERRO AO OBTER IP LOCAL, Verifique!! \n" + e, "Erro Separar", JOptionPane.ERROR_MESSAGE);
        }
        return "separacao_" + ia.getHostAddress() + "_" + ia.getHostName();
    }

    private boolean verificaPedidoAberto() {
        boolean condicao = true;
        List<IntConfiguracao> listConfig = queryIntegrador.listagemConfiguracaoPorValor(movenda.getCodmovenda());
        if (listConfig.size() > 1) {
            String ex = "";
            for (IntConfiguracao config : listConfig) {
                if (!config.getTipo().equals(retornaIpLocal())) {
                    ex = ex + config.getTipo() + "\n";
                }
            }
            JOptionPane.showMessageDialog(null, "O PEDIDO JÁ ESTÁ ABERTO EM OUTRA MAQUINA, Verifique!! \n" + ex, "Erro Separar", JOptionPane.ERROR_MESSAGE);
            condicao = false;
        }
        return condicao;
    }

    private boolean insereConfiguracaoParaSeparacao() {
        boolean condicao = true;
        List<IntConfiguracao> listConfig = queryIntegrador.listagemConfiguracaoproTipoConfiguracao(retornaIpLocal());
        if (listConfig.isEmpty()) {
            IntConfiguracao c = new IntConfiguracao();
            c.setTipo(retornaIpLocal());
            c.setDescricao("pedido em separação no pc");
            c.setDataAtualizacao(new Date(System.currentTimeMillis()));
            c.setValor(movenda.getCodmovenda());
            c.setDataCriacao(new Date(System.currentTimeMillis()));
            try {
                new IntConfiguracaoJpaController(Manager.getManagerIntegrador()).create(c);
            } catch (Exception ex) {
                condicao = false;
                JOptionPane.showMessageDialog(null, "HOUVE UM ERRO AO CRIAR CONFIGURAÇÃO, Verifique!! \n" + ex, "Erro Separar", JOptionPane.ERROR_MESSAGE);
            }
        } else if (listConfig.size() == 1) {
            for (IntConfiguracao config : listConfig) {
                config.setValor(movenda.getCodmovenda());
                try {
                    new IntConfiguracaoJpaController(Manager.getManagerIntegrador()).edit(config);
                } catch (Exception ex) {
                    condicao = false;
                    JOptionPane.showMessageDialog(null, "HOUVE UM ERRO AO EDITAR CONFIGURACAO, Verifique!! \n" + ex, "Erro Separar", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            int cont = 0;
            for (IntConfiguracao config : listConfig) {
                if (cont > 0) {
                    try {
                        new IntConfiguracaoJpaController(Manager.getManagerIntegrador()).destroy(config.getEntityId());
                    } catch (jpa.integrador.exceptions.NonexistentEntityException ex) {
                        condicao = false;
                        JOptionPane.showMessageDialog(null, "HOUVE UM ERRO AO EXCLUIR CONFIGURAÇÃO, Verifique!! \n" + ex, "Erro Separar", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
        return condicao;
    }

    private void buscaPedido() {
        jTextFieldSerial.setText("");
        jTextFieldSerial.setEnabled(false);
        jButtonExcluirSeria.setEnabled(false);
        this.listagemSaidasJDialog.setVisible(true);
        if (this.listagemSaidasJDialog.isCancelamento() == false) {
            movenda = this.listagemSaidasJDialog.getMoVenda();
            //listMovendaProd = queryCplus.listMovendaProd(movenda.getCodmovenda()); 
            //Laço altera a quantidade na nos produtos do pedido com referencia aos pacotes
            listSaidaSerial = new ArrayList<>();
            listMovendaProd = new ArrayList<>();
            for (Movendaprod p : queryCplus.listMovendaProd(movenda.getCodmovenda())) {
                BigDecimal q = p.getQuantidade();
                for (Unidade un : queryCplus.resultPorUnidadeProduto(p.getCodprod().getUnidade())) {
                    if (un.getFatorconversao().intValue() > 1) {
                        q = p.getQuantidade().divide(un.getFatorconversao());
                    }
                }
                p.setQuantidade(q);
                //carrega o estoque do produto
                p.setComissao(new BigDecimal(EstoqueCplus(p.getCodprod().getCodprod())));
                //carrega a localização do produto
                p.setCodigoeanproduto(setor(p.getCodprod()));
                listMovendaProd.add(p);
            }
            //Laço que carrega uma lista de Seriais de Saida caso haja
            //for (Movendaprod p : listMovendaProd) {
            for (SaidaSerial s : queryIntegrador.listPorSaida(movenda.getCodmovenda())) {
                listSaidaSerial.add(s);
            }
            //}
            //carrega a lista de codigos EAN do C-plus
            carregaListaCodigos();
            //////////////////////////////////////////// 

            String str = movenda.getFlagcancelada().toString();
            if ("N".equals(str)) {
                if (insereConfiguracaoParaSeparacao()) {
                    if (verificaPedidoAberto()) {
                        carregaTabelas();
                        pedidoSeparado(true);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "O pedido está cancelado, verifique!!! ", "Erro Separar", JOptionPane.ERROR_MESSAGE);
            }
            //jButtonCancelarSeparacao.setEnabled(false);
            jButtonPesquisaSaida.setEnabled(true);
            jButtonFechar.setEnabled(true);
        }//fim if adialog cancelado
    }

    private void criaLog(Date dataExecucao, String mensagem, String tipoLog) {
        IntLogs log = new IntLogs();
        log.setDataExecucao(dataExecucao);
        // log.setUltimaExecucao(dataExecucao);
        log.setMensagem(mensagem);
        log.setTipoLog(tipoLog);
        new IntLogsJpaController(Manager.getManagerIntegrador()).create(log);
    }

    private void gravarSaidaSerial() {
        for (SaidaSerial s : listSaidaSerial) {
            if (s.getIdSaidaSerial() == 0) {
                SaidaSerial mvps = new SaidaSerial();
                mvps.setCodSaida(s.getCodSaida());
                mvps.setCodSaidaProd(s.getCodSaidaProd());
                mvps.setDataSaida(new Date(System.currentTimeMillis()));
                mvps.setDevolvido(false);
                mvps.setIdSerial(s.getIdSerial());
                try {
                    new SaidaSerialJpaController(Manager.getManagerIntegrador()).create(mvps);

                } catch (Exception ex) {
                    tocarSomErro();
                    JOptionPane.showMessageDialog(null, "ERRO AO GRAVAR SERIAL, Verifique!! \n" + ex, "Erro Separar", JOptionPane.ERROR_MESSAGE);
                    this.listagemUsuarioJDialog.setVisible(true);
                }
            }
        }
        //Laço que carrega uma lista de Seriais de Saida caso haja
        listSaidaSerial.clear();
        for (SaidaSerial s : queryIntegrador.listPorSaida(movenda.getCodmovenda())) {
            listSaidaSerial.add(s);
        }
        jButtonFechar.setEnabled(true);
        jButtonPesquisaSaida.setEnabled(true);
        jButtonGravar.setEnabled(false);
        jTextFieldSerial.setEnabled(false);
        carregaTabelas();
        pedidoSeparado(true);
    }

    private void tocarSomErro() {
        //String com o caminho do arquivo ReproduzirAudio a ser tocado
        //String path = queryIntegrador.valorConfiguracao("caminho_ARQUIVO_AUDIO_ERRO");
        //new VariavelStatica().caminho_ARQUIVO_AUDIO_ERRO;
        //Instanciar um objeto File com o arquivo ReproduzirAudio
        File mp3File = new File(ConfiguracaoNoBD.getValorAudioErro());
        //Instancia do Objeto ReproduzirAudio, a qual criamos a classe.
        ReproduzirAudio musica = new ReproduzirAudio(mp3File);
        //Finalmente a chamada do método que toca a música
        musica.play();
    }

    /**
     * Função verifica se o pedido está separado
     *
     * @return true se já estiver separado false não separado ou não separado
     * completamente
     */
    private boolean pedidoSeparado(boolean val) {
        boolean condicao = false;
        //List<Movendaprod> listaProdutoPedido = queryCplus.listMovendaProd(movenda.getCodmovenda());
        int quanMovendaProd = 0;
        //int quantidadeSerial = queryIntegrador.listPorSaida(movenda.getCodmovenda()).size();
        int quantidadeSerial = listSaidaSerial.size();
        for (Movendaprod movProd : listMovendaProd) {
            //soma quantidades do pedido
            //quanMovendaProd = quanMovendaProd + quantidadePacote(movProd);
            quanMovendaProd = quanMovendaProd + movProd.getQuantidade().intValue();
            //soma seriais
            //quantidadeSerial = quantidadeSerial + queryIntegrador.listPorSaidaProd(movProd.getCodmovprod()).size();
        }
        jButtonExcluirSeria.setEnabled(false);
        // quantidadeSaidas = movendaprodserialList.size();
        // quantidadTotalPedido = quanMovendaProd;
        int tot = quanMovendaProd - quantidadeSerial;
        //jTextFieldItensFaltando.setText(String.valueOf(tot));

        if (quanMovendaProd == quantidadeSerial && val) {
            jTextFieldItensFaltando.setText(String.valueOf(tot));
            if (quanMovendaProd == queryIntegrador.listPorSaida(movenda.getCodmovenda()).size()) {
                jTextFieldItensFaltando.setBackground(format.stringParaColor(ConfiguracaoNoBD.getValorLinhaCompleto()));
                jTextFieldTextoAviso.setText("Pedido Totalmente Separado!");
                jTextFieldTextoAviso.setBackground(format.stringParaColor(ConfiguracaoNoBD.getValorLinhaCompleto()));
            } else {
                jTextFieldItensFaltando.setBackground(format.stringParaColor(ConfiguracaoNoBD.getValorLinhaCuidado()));
                jTextFieldTextoAviso.setText("Pedido pendente de GRAVAÇÃO!");
                jTextFieldTextoAviso.setBackground(format.stringParaColor(ConfiguracaoNoBD.getValorLinhaCuidado()));
            }
            jButtonSepararPedido.setEnabled(false);
            jButtonCancelarSeparacao.setEnabled(true);
            jButtonImprimirRomaneio.setEnabled(true);
            //jButtonPesquisaSaida.setEnabled(true);
            //jButtonFechar.setEnabled(true);
            jTextFieldSerial.setEnabled(false);
            //jButtonGravar.setEnabled(true);
            tocarSomFinalizado();
            condicao = true;
        } else {
            jTextFieldItensFaltando.setText(String.valueOf(tot));
            jTextFieldItensFaltando.setBackground(format.stringParaColor(ConfiguracaoNoBD.getValorLinhaIncompleto()));
            jTextFieldTextoAviso.setText("Aguardando Separação de Produtos!");
            jTextFieldTextoAviso.setBackground(format.stringParaColor(ConfiguracaoNoBD.getValorLinhaIncompleto()));
            jButtonImprimirRomaneio.setEnabled(false);
            jButtonSepararPedido.setEnabled(true);
            jButtonCancelarSeparacao.setEnabled(true);
            jButtonFechar.setEnabled(false);
            jButtonPesquisaSaida.setEnabled(false);
            jButtonGravar.setEnabled(false);
        }
        if (quanMovendaProd == quantidadeSerial) {
            String romaneio = "";
            for (Movendaprod vend : listMovendaProd) {
                romaneio = romaneio + vend.getCodprod().getCodigo() + ": ";
                //for (SaidaSerial sai : queryIntegrador.listPorSaidaProd(vend.getCodmovprod())) {
                for (SaidaSerial sai : listSaidaSerial) {
                    if (vend.getCodmovprod().equals(sai.getCodSaidaProd())) {
                        romaneio = romaneio + sai.getIdSerial().getSerial() + ", ";
                    }
                }
                romaneio = romaneio + "  ";
            }
            movenda.setObsnotafiscal(romaneio);
            try {
                new MovendaJpaController(Manager.getManagerCplus()).edit(movenda);
            } catch (NonexistentEntityException ex) {
                JOptionPane.showMessageDialog(null, "ERRO AO EDITAR MOVENDA, Verifique!! \n" + ex, "Erro Separar", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "ERRO AO EDITAR MOVENDA, Verifique!! \n" + ex, "Erro Separar", JOptionPane.ERROR_MESSAGE);
            }
        }
        return condicao;
    }

    private int quantidadePacote(Movendaprod movendaProd) {
        int quantidade = movendaProd.getQuantidade().intValue();
        for (Unidade un : queryCplus.resultPorUnidadeProduto(movendaProd.getCodprod().getUnidade())) {
            if (un.getFatorconversao().intValue() > 1) {
                quantidade = quantidade / un.getFatorconversao().intValue();
                jTextFieldMultiplo.setText(String.valueOf(un.getFatorconversao().intValue()));
            } else {
                jTextFieldMultiplo.setText("1");
            }
        }

        return quantidade;
    }

    private void tocarSomFinalizado() {
        //String com o caminho do arquivo ReproduzirAudio a ser tocado
        // String path = queryIntegrador.valorConfiguracao("caminho_ARQUIVO_AUDIO_FINALIZADO");
        // new VariavelStatica().caminho_ARQUIVO_AUDIO_FINALIZADO;
        //Instancia de um objeto File com o arquivo ReproduzirAudio
        File mp3File = new File(ConfiguracaoNoBD.getValorAudioFinalizado());
        //Instancia do Objeto ReproduzirAudio, a qual criamos a classe.
        ReproduzirAudio musica = new ReproduzirAudio(mp3File);
        //Finalmente a chamada do método que toca a música
        musica.play();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaidaSerialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaidaSerialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaidaSerialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaidaSerialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaidaSerialJFrame().setVisible(true);
            }
        });
    }

    private List<ListCodigoProduto> listCodigo;
    private List<SaidaSerial> listSaidaSerial;

    private Movenda movenda;
    private final ListagemSaidasJDialog listagemSaidasJDialog;
    private final ListagemUsuarioJDialog listagemUsuarioJDialog;
    private List<Movendaprod> listMovendaProd;
    private final QueryCplus queryCplus;
    private final QueryIntegrador queryIntegrador;
    private final ListagemProdutoJDialog listagemProdutoJDialog;
    private final FormataCampos format = new FormataCampos();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarSeparacao;
    private javax.swing.JButton jButtonEditarProduto;
    private javax.swing.JButton jButtonExcluirSeria;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonImprimirRomaneio;
    private javax.swing.JButton jButtonPesquisaSaida;
    private javax.swing.JButton jButtonSepararPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDigiteSerial;
    private javax.swing.JLabel jLabelItensFaltando;
    private javax.swing.JPanel jPanelConfiguracaoLista;
    private javax.swing.JPanel jPanelInformacoes;
    private javax.swing.JPanel jPanelPesquisas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableSaidaProd;
    private javax.swing.JTable jTableSeriasSeparados;
    private javax.swing.JTextField jTextFieldItensFaltando;
    private javax.swing.JTextField jTextFieldMultiplo;
    private javax.swing.JTextField jTextFieldSerial;
    private javax.swing.JTextField jTextFieldTextoAviso;
    // End of variables declaration//GEN-END:variables

}
